import {SdtfPrimitiveTypeGuard} from "@shapediver/sdk.sdtf-primitives";
import {SdtfTypeHintName} from "@shapediver/sdk.sdtf-v1";

import {
	ATTRIBUTE_VISUALIZATION,
	type Gradient,
	type IGradient,
	type INumberGradient,
	type IStringGradient,
} from "./interfaces/attribute-visualization";
import type {
	IAnimationData,
	IAnimationTrack,
} from "./interfaces/data/IAnimationData";
import type {IChunkData} from "./interfaces/data/IChunkData";
import type {ICustomData} from "./interfaces/data/ICustomData";
import {
	type IAttributeData,
	type IGeometryData,
	type IPrimitiveData,
	PRIMITIVE_MODE,
} from "./interfaces/data/IGeometryData";
import {
	type IAnchor,
	type IAnchorDataImage,
	type IAnchorDataText,
	type IHTMLElementAnchorData,
	type IHTMLElementAnchorUpdateProperties,
	type ITag2D,
	type ITag3D,
	TAG3D_JUSTIFICATION,
} from "./interfaces/data/IHTMLElementAnchorData";
import type {IInstanceData} from "./interfaces/data/IInstanceData";
import {
	ACCESSORCOMPONENTSIZE as ACCESSORCOMPONENTSIZE_V1,
	ACCESSORCOMPONENTTYPE as ACCESSORCOMPONENTTYPE_V1,
	ACCESSORTYPE as ACCESSORTYPE_V1,
	type IGLTF_v1,
	type IGLTF_v1_Accessor,
	type IGLTF_v1_Animation,
	type IGLTF_v1_Asset,
	type IGLTF_v1_Buffer,
	type IGLTF_v1_BufferView,
	type IGLTF_v1_Camera,
	type IGLTF_v1_Image,
	type IGLTF_v1_Material,
	type IGLTF_v1_Mesh,
	type IGLTF_v1_Node,
	type IGLTF_v1_Program,
	type IGLTF_v1_Sampler,
	type IGLTF_v1_Scene,
	type IGLTF_v1_Shader,
	type IGLTF_v1_Skin,
	type IGLTF_v1_Technique,
	type IGLTF_v1_Texture,
} from "./interfaces/data/gltfv1/IGLTF_v1";
import type {ISDGTF_v1} from "./interfaces/data/gltfv1/ISDGTF_v1";
import {
	ACCESSORCOMPONENTSIZE as ACCESSORCOMPONENTSIZE_V2,
	ACCESSORCOMPONENTTYPE as ACCESSORCOMPONENTTYPE_V2,
	ACCESSORTYPE as ACCESSORTYPE_V2,
	type IGLTF_v2,
	type IGLTF_v2_Accessor,
	type IGLTF_v2_Animation,
	type IGLTF_v2_Asset,
	type IGLTF_v2_Buffer,
	type IGLTF_v2_BufferView,
	type IGLTF_v2_Camera,
	type IGLTF_v2_Image,
	type IGLTF_v2_Material,
	type IGLTF_v2_Material_KHR_materials_pbrSpecularGlossiness,
	type IGLTF_v2_Mesh,
	type IGLTF_v2_Node,
	type IGLTF_v2_Primitive,
	type IGLTF_v2_Sampler,
	type IGLTF_v2_Scene,
	type IGLTF_v2_Skin,
	type IGLTF_v2_Texture,
	type ISHAPEDIVER_materials_preset,
} from "./interfaces/data/gltfv2/IGLTF_v2";
import {
	type IMapData,
	type IMapDataProperties,
	type IMapDataPropertiesDefinition,
	TEXTURE_FILTERING,
	TEXTURE_WRAPPING,
} from "./interfaces/data/material/IMapData";
import {
	type IMaterialAbstractData,
	type IMaterialAbstractDataProperties,
	type IMaterialAbstractDataPropertiesDefinition,
	MATERIAL_ALPHA,
	MATERIAL_SHADING,
	MATERIAL_SIDE,
	MATERIAL_TYPE,
} from "./interfaces/data/material/IMaterialAbstractData";
import type {
	IMaterialBasicLineData,
	IMaterialBasicLineDataProperties,
	IMaterialBasicLineDataPropertiesDefinition,
} from "./interfaces/data/material/IMaterialBasicLineData";
import type {
	IMaterialGemData,
	IMaterialGemDataProperties,
	IMaterialGemDataPropertiesDefinition,
} from "./interfaces/data/material/IMaterialGemDataProperties";
import type {
	IMaterialLambertData,
	IMaterialLambertDataProperties,
	IMaterialLambertDataPropertiesDefinition,
} from "./interfaces/data/material/IMaterialLambertData";
import type {
	IMaterialMultiPointData,
	IMaterialMultiPointDataProperties,
	IMaterialMultiPointDataPropertiesDefinition,
} from "./interfaces/data/material/IMaterialMultiPointData";
import type {
	IMaterialPhongData,
	IMaterialPhongDataProperties,
	IMaterialPhongDataPropertiesDefinition,
} from "./interfaces/data/material/IMaterialPhongData";
import type {
	IMaterialPointData,
	IMaterialPointDataProperties,
	IMaterialPointDataPropertiesDefinition,
} from "./interfaces/data/material/IMaterialPointData";
import type {
	IMaterialShadowData,
	IMaterialShadowDataProperties,
	IMaterialShadowDataPropertiesDefinition,
} from "./interfaces/data/material/IMaterialShadowData";
import type {
	IMaterialSpecularGlossinessData,
	IMaterialSpecularGlossinessDataProperties,
	IMaterialSpecularGlossinessDataPropertiesDefinition,
} from "./interfaces/data/material/IMaterialSpecularGlossinessDataProperties";
import type {
	IMaterialStandardData,
	IMaterialStandardDataProperties,
	IMaterialStandardDataPropertiesDefinition,
} from "./interfaces/data/material/IMaterialStandardData";
import type {
	IMaterialUnlitData,
	IMaterialUnlitDataProperties,
	IMaterialUnlitDataPropertiesDefinition,
} from "./interfaces/data/material/IMaterialUnlitData";
import type {IMaterialVariantsData} from "./interfaces/data/material/IMaterialVariantsData";
import type {
	IMaterialContentData,
	IMaterialContentDataV1,
	IMaterialContentDataV2,
	IMaterialContentDataV3,
	IPresetMaterialDefinition,
	ITexture,
} from "./interfaces/data/material/interfaces";
import type {
	ISDTF,
	ISDTF_Accessor,
	ISDTF_Attribute,
	ISDTF_Buffer,
	ISDTF_BufferView,
	ISDTF_Chunk,
	ISDTF_Item,
	ISDTF_Node,
	ISDTF_TypeHint,
} from "./interfaces/data/sdtf/ISDTF";
import type {EventResponseMapping} from "./interfaces/events/EventResponseMapping";
import {
	EVENTTYPE,
	EVENTTYPE_CAMERA,
	EVENTTYPE_DRAWING_TOOLS,
	EVENTTYPE_INTERACTION,
	EVENTTYPE_OUTPUT,
	EVENTTYPE_PARAMETER,
	EVENTTYPE_RENDERING,
	EVENTTYPE_SCENE,
	EVENTTYPE_SESSION,
	EVENTTYPE_TASK,
	EVENTTYPE_TRANSFORMATION_TOOLS,
	EVENTTYPE_VIEWPORT,
	type MainEventTypes,
} from "./interfaces/events/EventTypes";
import type {ICameraEvent} from "./interfaces/events/ICameraEvent";
import type {IEvent} from "./interfaces/events/IEvent";
import type {IOutputEvent} from "./interfaces/events/IOutputEvent";
import type {IParameterEvent} from "./interfaces/events/IParameterEvent";
import type {IRenderingEvent} from "./interfaces/events/IRenderingEvent";
import type {ISceneEvent} from "./interfaces/events/ISceneEvent";
import type {
	ISessionErrorEvent,
	ISessionEvent,
} from "./interfaces/events/ISessionEvent";
import {
	type ITaskEvent,
	type ITaskEventDescription,
	TASK_CATEGORY,
	TASK_CATEGORY_SESSION_CUSTOMIZATION_CATEGORY,
	TASK_TYPE,
	type TaskCategoryTypes,
} from "./interfaces/events/ITaskEvent";
import type {IViewportEvent} from "./interfaces/events/IViewportEvent";
import type {IBox} from "./interfaces/math/IBox";
import type {IGeometry} from "./interfaces/math/IGeometry";
import type {IPlane} from "./interfaces/math/IPlane";
import type {ISphere} from "./interfaces/math/ISphere";
import type {ISpherical} from "./interfaces/math/ISpherical";
import type {ITriangle} from "./interfaces/math/ITriangle";
import type {
	DraggingParameterValue,
	IDraggableObject,
	IDraggingParameterProps,
} from "./interfaces/parameter/IDraggingParameterSettings";
import {
	type DrawingParameterValue,
	type IControlSettings,
	IDrawingParameterJsonSchema,
	type IDrawingParameterSettings,
	type IVisualizationSettings,
	validateDrawingParameterSettings,
} from "./interfaces/parameter/IDrawingParametersSettings";
import type {
	GumballTransformParameterValue,
	IGumballTransformParameterProps,
} from "./interfaces/parameter/IGumballTransformParameterSettings";
import {
	IDraggingParameterJsonSchema,
	IDraggingParameterPropsJsonSchema,
	IGumballTransformParameterJsonSchema,
	IGumballTransformParameterPropsJsonSchema,
	IInteractionParameterJsonSchema,
	type IInteractionParameterProps,
	type IInteractionParameterSettings,
	IRectangleTransformParameterJsonSchema,
	IRectangleTransformParameterPropsJsonSchema,
	ISelectionParameterJsonSchema,
	ISelectionParameterPropsJsonSchema,
	type InteractionEffect,
	type InteractionParameterSettingsType,
	validateDraggingParameterSettings,
	validateGumballTransformParameterSettings,
	validateInteractionParameterSettings,
	validateRectangleTransformParameterSettings,
	validateSelectionParameterSettings,
} from "./interfaces/parameter/IInteractionParameterSettings";
import type {
	IRectangleTransformParameterProps,
	RectangleTransformParameterValue,
} from "./interfaces/parameter/IRectangleTransformParameterSettings";
import type {
	ICameraPlaneRestrictionDefinition,
	IGeometryRestrictionDefinition,
	ILineRestrictionDefinition,
	IPlaneRestrictionDefinition,
	IPointRestrictionDefinition,
	IRestrictionDefinition,
	RestrictionDefinition,
	Rotation,
} from "./interfaces/parameter/IRestrictionSettings";
import type {
	ISelectionParameterProps,
	SelectionParameterValue,
} from "./interfaces/parameter/ISelectionParameterSettings";
import type {
	IBoxSelectionIntersection,
	IIntersectionDefinition,
	IRayTracingIntersection,
} from "./interfaces/renderingEngine/IIntersection";
import type {IIntersectionFilter} from "./interfaces/renderingEngine/IIntersectionFilter";
import {
	ANTI_ALIASING_TECHNIQUE,
	type IBloomEffectDefinition,
	type IChromaticAberrationEffectDefinition,
	type IDepthOfFieldEffectDefinition,
	type IDotScreenEffectDefinition,
	type IGodRaysEffectDefinition,
	type IGridEffectDefinition,
	type IHBAOEffectDefinition,
	type IHueSaturationEffectDefinition,
	type INoiseEffectDefinition,
	type IOutlineEffectDefinition,
	type IPixelationEffectDefinition,
	type IPostProcessingEffectDefinition,
	type IPostProcessingEffectsArray,
	type ISSAOEffectDefinition,
	type IScanlineEffectDefinition,
	type ISelectiveBloomEffectDefinition,
	type ISepiaEffectDefinition,
	type ITiltShiftEffectDefinition,
	type IVignetteEffectDefinition,
	POST_PROCESSING_EFFECT_TYPE,
} from "./interfaces/renderingEngine/IPostProcessingEffectDefinitions";
import type {IPulseEffectDefinition} from "./interfaces/renderingEngine/IPulseEffectDefinition";
import type {IRay} from "./interfaces/renderingEngine/IRay";
import {
	CAMERA_TYPE,
	type CameraProperties,
	type ICameraOptions,
	ORTHOGRAPHIC_CAMERA_DIRECTION,
	type OrthographicCameraProperties,
	type PerspectiveCameraProperties,
} from "./interfaces/renderingEngine/cameraTypes";
import {
	BUSY_MODE_DISPLAY,
	ENVIRONMENT_MAP_PBR_MODE,
	FLAG_TYPE,
	RENDERER_TYPE,
	SPINNER_POSITIONING,
	TEXTURE_ENCODING,
	TONE_MAPPING,
	VISIBILITY_MODE,
} from "./interfaces/renderingEngine/enums";
import type {ISDTFAttributeVisualizationData} from "./interfaces/sdtf/ISDTFAttributeVisualizationData";
import type {
	ISDTFAttributeData,
	ISDTFAttributesData,
} from "./interfaces/sdtf/ISDTFAttributesData";
import type {ISDTFItemData} from "./interfaces/sdtf/ISDTFItemData";
import type {
	ISDTFOverview,
	ISDTFOverviewData,
} from "./interfaces/sdtf/ISDTFOverviewData";
import type {ITree} from "./interfaces/tree-node/ITree";
import type {
	ITransformation,
	ITreeNode,
} from "./interfaces/tree-node/ITreeNode";
import type {ITreeNodeData} from "./interfaces/tree-node/ITreeNodeData";
import {
	type Color,
	type ISessionSettingsSections,
	type ISettingsSections,
	type IViewportSettingsSections,
	PARAMETER_TYPE,
	PARAMETER_VISUALIZATION,
	type SDImageBitmap,
	SESSION_SETTINGS_MODE,
	type SessionCreationDefinition,
	type ViewportCreationDefinition,
} from "./types";

export {
	ANTI_ALIASING_TECHNIQUE,
	ATTRIBUTE_VISUALIZATION,
	BUSY_MODE_DISPLAY,
	CAMERA_TYPE,
	ENVIRONMENT_MAP_PBR_MODE,
	EVENTTYPE,
	EVENTTYPE_CAMERA,
	EVENTTYPE_DRAWING_TOOLS,
	EVENTTYPE_INTERACTION,
	EVENTTYPE_OUTPUT,
	EVENTTYPE_PARAMETER,
	EVENTTYPE_RENDERING,
	EVENTTYPE_SCENE,
	EVENTTYPE_SESSION,
	EVENTTYPE_TASK,
	EVENTTYPE_TRANSFORMATION_TOOLS,
	EVENTTYPE_VIEWPORT,
	FLAG_TYPE,
	IDraggingParameterJsonSchema,
	IDraggingParameterPropsJsonSchema,
	IDrawingParameterJsonSchema,
	IGumballTransformParameterJsonSchema,
	IGumballTransformParameterPropsJsonSchema,
	IInteractionParameterJsonSchema,
	IRectangleTransformParameterJsonSchema,
	IRectangleTransformParameterPropsJsonSchema,
	ISelectionParameterJsonSchema,
	ISelectionParameterPropsJsonSchema,
	MATERIAL_ALPHA,
	MATERIAL_SHADING,
	MATERIAL_SIDE,
	MATERIAL_TYPE,
	ORTHOGRAPHIC_CAMERA_DIRECTION,
	PARAMETER_TYPE,
	PARAMETER_VISUALIZATION,
	POST_PROCESSING_EFFECT_TYPE,
	PRIMITIVE_MODE,
	RENDERER_TYPE,
	SdtfTypeHintName as SDTF_TYPEHINT,
	SESSION_SETTINGS_MODE,
	SPINNER_POSITIONING,
	SdtfPrimitiveTypeGuard,
	TASK_CATEGORY,
	TASK_CATEGORY_SESSION_CUSTOMIZATION_CATEGORY,
	TASK_TYPE,
	TEXTURE_ENCODING,
	TEXTURE_FILTERING,
	TEXTURE_WRAPPING,
	TONE_MAPPING,
	VISIBILITY_MODE,
	validateDraggingParameterSettings,
	validateDrawingParameterSettings,
	validateGumballTransformParameterSettings,
	validateInteractionParameterSettings,
	validateRectangleTransformParameterSettings,
	validateSelectionParameterSettings,
};

export type {
	CameraProperties,
	Color,
	DraggingParameterValue,
	DrawingParameterValue,
	EventResponseMapping,
	Gradient,
	GumballTransformParameterValue,
	IAnchorDataImage,
	IAnchorDataText,
	IAnimationData,
	IAnimationTrack,
	IAttributeData,
	IBloomEffectDefinition,
	IBox,
	IBoxSelectionIntersection,
	ICameraEvent,
	ICameraOptions,
	ICameraPlaneRestrictionDefinition,
	IChromaticAberrationEffectDefinition,
	IChunkData,
	IControlSettings,
	ICustomData,
	IDepthOfFieldEffectDefinition,
	IDotScreenEffectDefinition,
	IDraggableObject,
	IDraggingParameterProps,
	IDrawingParameterSettings,
	IEvent,
	IGeometry,
	IGeometryData,
	IGeometryRestrictionDefinition,
	IGodRaysEffectDefinition,
	IGradient,
	IGridEffectDefinition,
	IGumballTransformParameterProps,
	IHBAOEffectDefinition,
	IHTMLElementAnchorData,
	IHTMLElementAnchorUpdateProperties,
	IHueSaturationEffectDefinition,
	IInstanceData,
	IInteractionParameterProps,
	IInteractionParameterSettings,
	IIntersectionDefinition,
	IIntersectionFilter,
	ILineRestrictionDefinition,
	IMapData,
	IMapDataProperties,
	IMapDataPropertiesDefinition,
	IMaterialAbstractData,
	IMaterialAbstractDataProperties,
	IMaterialAbstractDataPropertiesDefinition,
	IMaterialBasicLineData,
	IMaterialBasicLineDataProperties,
	IMaterialBasicLineDataPropertiesDefinition,
	IMaterialGemData,
	IMaterialGemDataProperties,
	IMaterialGemDataPropertiesDefinition,
	IMaterialLambertData,
	IMaterialLambertDataProperties,
	IMaterialLambertDataPropertiesDefinition,
	IMaterialMultiPointData,
	IMaterialMultiPointDataProperties,
	IMaterialMultiPointDataPropertiesDefinition,
	IMaterialPhongData,
	IMaterialPhongDataProperties,
	IMaterialPhongDataPropertiesDefinition,
	IMaterialPointData,
	IMaterialPointDataProperties,
	IMaterialPointDataPropertiesDefinition,
	IMaterialShadowData,
	IMaterialShadowDataProperties,
	IMaterialShadowDataPropertiesDefinition,
	IMaterialSpecularGlossinessData,
	IMaterialSpecularGlossinessDataProperties,
	IMaterialSpecularGlossinessDataPropertiesDefinition,
	IMaterialStandardData,
	IMaterialStandardDataProperties,
	IMaterialStandardDataPropertiesDefinition,
	IMaterialUnlitData,
	IMaterialUnlitDataProperties,
	IMaterialUnlitDataPropertiesDefinition,
	IMaterialVariantsData,
	INoiseEffectDefinition,
	INumberGradient,
	IOutlineEffectDefinition,
	IOutputEvent,
	IParameterEvent,
	IPixelationEffectDefinition,
	IPlane,
	IPlaneRestrictionDefinition,
	IPointRestrictionDefinition,
	IPostProcessingEffectDefinition,
	IPostProcessingEffectsArray,
	IPrimitiveData,
	IPulseEffectDefinition,
	IRay,
	IRayTracingIntersection,
	IRectangleTransformParameterProps,
	IRenderingEvent,
	IRestrictionDefinition,
	ISDTFAttributeData,
	ISDTFAttributeVisualizationData,
	ISDTFAttributesData,
	ISDTFItemData,
	ISDTFOverview,
	ISDTFOverviewData,
	ISSAOEffectDefinition,
	IScanlineEffectDefinition,
	ISceneEvent,
	ISelectionParameterProps,
	ISelectiveBloomEffectDefinition,
	ISepiaEffectDefinition,
	ISessionErrorEvent,
	ISessionEvent,
	ISessionSettingsSections,
	ISettingsSections,
	ISphere,
	ISpherical,
	IStringGradient,
	ITaskEvent,
	ITaskEventDescription,
	ITiltShiftEffectDefinition,
	ITransformation,
	ITree,
	ITreeNode,
	ITreeNodeData,
	ITriangle,
	IViewportEvent,
	IViewportSettingsSections,
	IVignetteEffectDefinition,
	IVisualizationSettings,
	InteractionEffect,
	InteractionParameterSettingsType,
	MainEventTypes,
	OrthographicCameraProperties,
	PerspectiveCameraProperties,
	RectangleTransformParameterValue,
	RestrictionDefinition,
	Rotation,
	SDImageBitmap,
	SelectionParameterValue,
	SessionCreationDefinition,
	TaskCategoryTypes,
	ViewportCreationDefinition,
};

export {
	ACCESSORCOMPONENTSIZE_V1,
	ACCESSORCOMPONENTSIZE_V2,
	ACCESSORCOMPONENTTYPE_V1,
	ACCESSORCOMPONENTTYPE_V2,
	ACCESSORTYPE_V1,
	ACCESSORTYPE_V2,
	TAG3D_JUSTIFICATION,
};

export type {
	IAnchor,
	IGLTF_v1,
	IGLTF_v1_Accessor,
	IGLTF_v1_Animation,
	IGLTF_v1_Asset,
	IGLTF_v1_Buffer,
	IGLTF_v1_BufferView,
	IGLTF_v1_Camera,
	IGLTF_v1_Image,
	IGLTF_v1_Material,
	IGLTF_v1_Mesh,
	IGLTF_v1_Node,
	IGLTF_v1_Program,
	IGLTF_v1_Sampler,
	IGLTF_v1_Scene,
	IGLTF_v1_Shader,
	IGLTF_v1_Skin,
	IGLTF_v1_Technique,
	IGLTF_v1_Texture,
	IGLTF_v2,
	IGLTF_v2_Accessor,
	IGLTF_v2_Animation,
	IGLTF_v2_Asset,
	IGLTF_v2_Buffer,
	IGLTF_v2_BufferView,
	IGLTF_v2_Camera,
	IGLTF_v2_Image,
	IGLTF_v2_Material,
	IGLTF_v2_Material_KHR_materials_pbrSpecularGlossiness,
	IGLTF_v2_Mesh,
	IGLTF_v2_Node,
	IGLTF_v2_Primitive,
	IGLTF_v2_Sampler,
	IGLTF_v2_Scene,
	IGLTF_v2_Skin,
	IGLTF_v2_Texture,
	IMaterialContentData,
	IMaterialContentDataV1,
	IMaterialContentDataV2,
	IMaterialContentDataV3,
	IPresetMaterialDefinition,
	ISDGTF_v1,
	ISDTF,
	ISDTF_Accessor,
	ISDTF_Attribute,
	ISDTF_Buffer,
	ISDTF_BufferView,
	ISDTF_Chunk,
	ISDTF_Item,
	ISDTF_Node,
	ISDTF_TypeHint,
	ISHAPEDIVER_materials_preset,
	ITag2D,
	ITag3D,
	ITexture,
};
