import {Page, test as base, expect} from "@playwright/test";
import * as fs from "fs";
import * as path from "path";

/**
 * GPU-instancing tests. The .glb assets are generated by
 * tests/instancing/generate-assets.js and served to the page via request
 * interception, so no external hosting is involved.
 */

const name = "instancing";
const ASSET_HOST = "https://instancing-assets.viewertests.invalid";
const assetsDir = path.join(__dirname, "assets");

const test = base.extend<{}, {workerPage: Page}>({
	workerPage: [
		async ({browser}, use) => {
			const context = await browser.newContext({
				viewport: {width: 1280, height: 720},
				deviceScaleFactor: 1,
			});
			const page = await context.newPage();

			// Serve the generated test assets from disk.
			await page.route(`${ASSET_HOST}/**`, async (route) => {
				const url = new URL(route.request().url());
				const assetPath = path.join(
					assetsDir,
					path.basename(url.pathname),
				);
				if (!fs.existsSync(assetPath)) {
					await route.fulfill({status: 404});
					return;
				}
				await route.fulfill({
					status: 200,
					contentType: "model/gltf-binary",
					body: fs.readFileSync(assetPath),
				});
			});

			await page.goto("test-cdn/index.html");

			await page.evaluate(async () => {
				const SDV = (<any>window).SDV;
				const DataEngine = (<any>window).SDV.DataEngine;

				const viewer = await SDV.createViewport({
					canvas: <HTMLCanvasElement>(
						document.getElementById("canvas")
					),
					id: "myViewer",
					branding: {
						backgroundColor: "rgb(3, 5, 49)",
					},
				});
				// Keep this explicit so the fixture is independent of caller overrides.
				viewer.gpuInstancing.enabled = true;
				viewer.beautyRenderDelay = 100;
				viewer.beautyRenderBlendingDuration = 100;
				viewer.shadows = false;
				viewer.physicallyCorrectLights = true;
				viewer.groundPlaneVisibility = false;
				viewer.gridVisibility = false;
				viewer.environmentMap = SDV.ENVIRONMENT_MAP.NEUTRAL;
				(<any>window).viewer = viewer;

				await new Promise<void>((resolve) => {
					SDV.addListener(SDV.EVENTTYPE.TASK.TASK_END, (e: any) => {
						if (e.type === SDV.TASK_TYPE.ENVIRONMENT_MAP_LOADING)
							resolve();
					});
				});

				const renderedP = () =>
					new Promise<void>((resolve) => {
						SDV.addListener(
							SDV.EVENTTYPE.RENDERING.BEAUTY_RENDERING_FINISHED,
							() => resolve(),
						);
					});

				let currentNode: any;
				(<any>window).addGLTF = async (uri: string) => {
					const node = await DataEngine.instance.loadContent({
						format: "gltf",
						href: uri,
					});
					const renderingP = renderedP();
					if (currentNode) SDV.sceneTree.removeNode(currentNode);
					currentNode = node;
					SDV.sceneTree.addNode(currentNode);
					SDV.sceneTree.root.updateVersion();
					viewer.show = true;
					await renderingP;
					await viewer.camera!.zoomTo(undefined, {duration: 0});
					await new Promise<void>((resolve) => {
						SDV.addListener(
							SDV.EVENTTYPE.RENDERING.BEAUTY_RENDERING_FINISHED,
							() => resolve(),
						);
						viewer.render();
					});
				};

				/** Renders and waits for the beauty pass. */
				(<any>window).rerender = async () => {
					SDV.sceneTree.root.updateVersion();
					await new Promise<void>((resolve) => {
						SDV.addListener(
							SDV.EVENTTYPE.RENDERING.BEAUTY_RENDERING_FINISHED,
							() => resolve(),
						);
						viewer.render();
					});
				};

				/** Finds a tree node by name (depth-first). */
				(<any>window).findNode = (nodeName: string) => {
					const search = (node: any): any => {
						if (node.name === nodeName) return node;
						for (const child of node.children) {
							const found = search(child);
							if (found) return found;
						}
						return undefined;
					};
					return search(SDV.sceneTree.root);
				};
			});

			await use(page);
			await context.close();
		},
		{scope: "worker"},
	],
});

test.describe("GPU instancing", () => {
	test.describe.configure({mode: "serial"});

	test("duplicated meshes are batched with per-instance colors", async ({
		workerPage,
	}) => {
		await workerPage.evaluate(async (uri: string) => {
			await (<any>window).addGLTF(uri);
		}, `${ASSET_HOST}/duplicated-boxes.glb`);

		// 9 opaque duplicated boxes → one group; the tetrahedron (unique) and
		// the 2 transparent boxes are excluded.
		const stats = await workerPage.evaluate(
			() => (<any>window).viewer.gpuInstancing.stats,
		);
		expect(stats.groupCount).toBe(1);
		expect(stats.instanceCount).toBe(9);

		await expect(workerPage).toHaveScreenshot(
			name + "/duplicated-boxes.png",
			{animations: "allow"},
		);
	});

	test("hiding one node hides only its instance", async ({workerPage}) => {
		await workerPage.evaluate(async () => {
			const node = (<any>window).findNode("box_node_4");
			node.visible = false;
			await (<any>window).rerender();
		});

		const stats = await workerPage.evaluate(
			() => (<any>window).viewer.gpuInstancing.stats,
		);
		expect(stats.instanceCount).toBe(9);

		await expect(workerPage).toHaveScreenshot(
			name + "/duplicated-boxes-hidden-instance.png",
			{animations: "allow"},
		);

		await workerPage.evaluate(async () => {
			const node = (<any>window).findNode("box_node_4");
			node.visible = true;
			await (<any>window).rerender();
		});
	});

	test("interaction material highlights only one instance", async ({
		workerPage,
	}) => {
		await workerPage.evaluate(async (uri: string) => {
			await (<any>window).addGLTF(uri);
			const SDV = (<any>window).SDV;
			const node = (<any>window).findNode("box_node_4");
			const geometryData = node.data.find(
				(d: any) => d.instanceHash !== undefined,
			);
			geometryData.effectMaterials.push({
				material: new SDV.MaterialStandardData({color: "#ff00ff"}),
				token: "test-highlight",
			});
			(<any>window).viewer.updateGeometryData(geometryData);
			await (<any>window).rerender();
		}, `${ASSET_HOST}/duplicated-boxes.glb`);

		await expect(workerPage).toHaveScreenshot(
			name + "/duplicated-boxes-highlight.png",
			{animations: "allow"},
		);

		// Remove the highlight again; the instance returns to its batch.
		await workerPage.evaluate(async () => {
			const node = (<any>window).findNode("box_node_4");
			const geometryData = node.data.find(
				(d: any) => d.instanceHash !== undefined,
			);
			geometryData.effectMaterials.pop();
			(<any>window).viewer.updateGeometryData(geometryData);
			await (<any>window).rerender();
		});
		const stats = await workerPage.evaluate(
			() => (<any>window).viewer.gpuInstancing.stats,
		);
		expect(stats.effectMeshCount).toBe(0);

		await expect(workerPage).toHaveScreenshot(
			name + "/duplicated-boxes.png",
			{animations: "allow"},
		);
	});

	test("a mesh shared by several nodes is batched", async ({workerPage}) => {
		await workerPage.evaluate(async (uri: string) => {
			await (<any>window).addGLTF(uri);
		}, `${ASSET_HOST}/shared-mesh-boxes.glb`);

		const stats = await workerPage.evaluate(
			() => (<any>window).viewer.gpuInstancing.stats,
		);
		expect(stats.groupCount).toBe(1);
		expect(stats.instanceCount).toBe(9);

		await expect(workerPage).toHaveScreenshot(
			name + "/shared-mesh-boxes.png",
			{animations: "allow"},
		);
	});

	test("baked transforms are extracted into instances", async ({
		workerPage,
	}) => {
		await workerPage.evaluate(async (uri: string) => {
			await (<any>window).addGLTF(uri);
		}, `${ASSET_HOST}/baked-boxes.glb`);

		const stats = await workerPage.evaluate(
			() => (<any>window).viewer.gpuInstancing.stats,
		);
		expect(stats.groupCount).toBe(1);
		expect(stats.instanceCount).toBe(6);

		await expect(workerPage).toHaveScreenshot(name + "/baked-boxes.png", {
			animations: "allow",
		});
	});

	test("disabling instancing falls back to regular meshes", async ({
		workerPage,
	}) => {
		await workerPage.evaluate(async (uri: string) => {
			(<any>window).viewer.gpuInstancing.enabled = false;
			await (<any>window).addGLTF(uri);
		}, `${ASSET_HOST}/duplicated-boxes.glb`);

		const stats = await workerPage.evaluate(
			() => (<any>window).viewer.gpuInstancing.stats,
		);
		expect(stats.groupCount).toBe(0);

		await expect(workerPage).toHaveScreenshot(
			name + "/duplicated-boxes.png",
			{animations: "allow"},
		);

		await workerPage.evaluate(() => {
			(<any>window).viewer.gpuInstancing.enabled = true;
		});
	});

	test("enabling instancing after load converts already-loaded meshes", async ({
		workerPage,
	}) => {
		await workerPage.evaluate(async (uri: string) => {
			(<any>window).viewer.gpuInstancing.enabled = false;
			await (<any>window).addGLTF(uri);
		}, `${ASSET_HOST}/duplicated-boxes.glb`);

		let stats = await workerPage.evaluate(
			() => (<any>window).viewer.gpuInstancing.stats,
		);
		expect(stats.groupCount).toBe(0);

		// Turn on instancing after the scene has already rendered.
		await workerPage.evaluate(async () => {
			(<any>window).viewer.gpuInstancing.enabled = true;
			await (<any>window).rerender();
		});

		stats = await workerPage.evaluate(
			() => (<any>window).viewer.gpuInstancing.stats,
		);
		expect(stats.groupCount).toBe(1);
		expect(stats.instanceCount).toBe(9);

		await expect(workerPage).toHaveScreenshot(
			name + "/duplicated-boxes.png",
			{animations: "allow"},
		);
	});

	test("toggling instancing rebinds an active outline selection", async ({
		workerPage,
	}) => {
		const selectionState = await workerPage.evaluate(
			async (uri: string) => {
				const SDV = (<any>window).SDV;
				const viewer = (<any>window).viewer;
				viewer.gpuInstancing.enabled = true;
				await (<any>window).addGLTF(uri);

				const token = viewer.postProcessing.addEffect({
					properties: {
						edgeStrength: 10,
						visibleEdgeColor: "#ff0000",
						hiddenEdgeColor: "#22090a",
					},
					type: SDV.POST_PROCESSING_EFFECT_TYPE.OUTLINE,
				});
				const node = (<any>window).findNode("box_node_4");
				viewer.postProcessing.outlineEffects[token].addSelection(node);
				await (<any>window).rerender();

				const describeSelection = () => {
					const effect = viewer.postProcessing.getEffect(token);
					const objects = [...effect.selection];
					return {
						count: objects.length,
						inScene: objects.every(
							(object: {parent: unknown}) =>
								object.parent !== null,
						),
						instanced: objects.some(
							(object: {isInstancedMesh?: boolean}) =>
								object.isInstancedMesh === true,
						),
					};
				};

				const afterEnable = describeSelection();
				viewer.gpuInstancing.enabled = false;
				await (<any>window).rerender();
				const afterDisable = describeSelection();
				viewer.gpuInstancing.enabled = true;
				await (<any>window).rerender();
				const afterReenable = describeSelection();
				return {afterEnable, afterDisable, afterReenable};
			},
			`${ASSET_HOST}/duplicated-boxes.glb`,
		);

		expect(selectionState.afterEnable.count).toBeGreaterThan(0);
		expect(selectionState.afterEnable.inScene).toBe(true);
		expect(selectionState.afterEnable.instanced).toBe(true);
		expect(selectionState.afterDisable.count).toBeGreaterThan(0);
		expect(selectionState.afterDisable.inScene).toBe(true);
		expect(selectionState.afterDisable.instanced).toBe(false);
		expect(selectionState.afterReenable.count).toBeGreaterThan(0);
		expect(selectionState.afterReenable.inScene).toBe(true);
		expect(selectionState.afterReenable.instanced).toBe(true);
	});

	test("pointer move followed by selection hits an instanced descendant", async ({
		workerPage,
	}) => {
		const pageErrors: string[] = [];
		workerPage.on("pageerror", (error) => pageErrors.push(error.message));
		const target = await workerPage.evaluate(async (uri: string) => {
			await (<any>window).addGLTF(uri);
			const SDV = (<any>window).SDV;
			const SDVInteractions = (<any>window).SDVInteractions;
			const viewer = (<any>window).viewer;
			const node = (<any>window).findNode("box_node_4");
			const owner = node.parent;
			owner.addData(new SDVInteractions.InteractionData({select: true}));

			const interactionEngine = new SDVInteractions.InteractionEngine(
				viewer,
			);
			const selectManager = new SDVInteractions.SelectManager(undefined, {
				type: "pulse",
				color: "#ff00ff",
				intensity: 0.8,
				pulseSpeed: 2,
			});
			interactionEngine.addInteractionManager(selectManager);

			(<any>window).selectedOwner = new Promise<string>((resolve) => {
				SDV.addListener(
					SDV.EVENTTYPE.INTERACTION.SELECT_ON,
					(event: any) => resolve(event.node.name),
				);
			});

			const box = node.boundingBoxViewport[viewer.id];
			const point = [
				(box.min[0] + box.max[0]) / 2,
				(box.min[1] + box.max[1]) / 2,
				(box.min[2] + box.max[2]) / 2,
			];
			const projected = viewer.convert3Dto2D(point).client;
			return {x: projected[0], y: projected[1], ownerName: owner.name};
		}, `${ASSET_HOST}/duplicated-boxes.glb`);

		// AppBuilder performs a hover raycast before the click. The old shared
		// processed-mesh set made the following down/up raycasts skip the batch.
		await workerPage.mouse.move(target.x, target.y);
		await workerPage.mouse.click(target.x, target.y);
		const selectedOwner = await workerPage.evaluate(() =>
			Promise.race([
				(<any>window).selectedOwner,
				new Promise((_, reject) =>
					setTimeout(
						() => reject(new Error("selection timeout")),
						2000,
					),
				),
			]),
		);
		expect(selectedOwner).toBe(target.ownerName);

		const pulseState = await workerPage.evaluate(async () => {
			const node = (<any>window).findNode("box_node_4");
			const geometry = node.data.find(
				(data: any) => data.instanceHash !== undefined,
			);
			const mesh = geometry.convertedObject[(<any>window).viewer.id];
			const key = `${node.id}:${geometry.id}`;
			const index = mesh.userData.instanceKeys.indexOf(key);
			const read = () => [
				mesh.instanceColor.getX(index),
				mesh.instanceColor.getY(index),
				mesh.instanceColor.getZ(index),
			];
			const first = read();
			let second = first;
			let changed = false;
			for (let sample = 0; sample < 20 && !changed; sample++) {
				await new Promise((resolve) => setTimeout(resolve, 50));
				second = read();
				changed = first.some(
					(value: number, index: number) =>
						Math.abs(value - second[index]) > 0.0001,
				);
			}
			return {
				index,
				effectCount: geometry.effectPulses.length,
				changed,
			};
		});
		expect(pulseState.index).toBeGreaterThanOrEqual(0);
		expect(pulseState.effectCount).toBe(1);
		expect(pulseState.changed).toBe(true);
		expect(pageErrors).toEqual([]);
	});

	test("mirrored occurrences switch safely between regular and instanced rendering", async ({
		workerPage,
	}) => {
		const counts = await workerPage.evaluate(async (uri: string) => {
			await (<any>window).addGLTF(uri);
			const viewer = (<any>window).viewer;
			const node = (<any>window).findNode("box_node_4");
			const before = viewer.gpuInstancing.stats.instanceCount;
			const matrix = (<any>window).GL_MATRIX.mat4.fromScaling(
				(<any>window).GL_MATRIX.mat4.create(),
				[-1, 1, 1],
			);
			node.addTransformation({id: "test-mirror", matrix});
			viewer.updateNodeTransformation(node);
			const mirrored = viewer.gpuInstancing.stats.instanceCount;
			node.removeTransformation(node.getTransformation("test-mirror"));
			viewer.updateNodeTransformation(node);
			const restored = viewer.gpuInstancing.stats.instanceCount;
			return {before, mirrored, restored};
		}, `${ASSET_HOST}/duplicated-boxes.glb`);

		expect(counts.before).toBe(9);
		expect(counts.mirrored).toBe(8);
		expect(counts.restored).toBe(9);
	});

	test("render-order and shadow variants use separate batches", async ({
		workerPage,
	}) => {
		const state = await workerPage.evaluate(async (uri: string) => {
			await (<any>window).addGLTF(uri);
			const viewer = (<any>window).viewer;
			const node = (<any>window).findNode("box_node_4");
			const geometry = node.data.find(
				(data: any) => data.instanceHash !== undefined,
			);
			geometry.renderOrder = 7;
			geometry.castShadow = false;
			geometry.receiveShadow = false;
			viewer.updateNode(node);
			const mesh = geometry.convertedObject[viewer.id];
			return {
				groupCount: viewer.gpuInstancing.stats.groupCount,
				renderOrder: mesh.renderOrder,
				castShadow: mesh.castShadow,
				receiveShadow: mesh.receiveShadow,
			};
		}, `${ASSET_HOST}/duplicated-boxes.glb`);

		expect(state).toEqual({
			groupCount: 2,
			renderOrder: 7,
			castShadow: false,
			receiveShadow: false,
		});
	});

	test("multiple outline and bloom effects keep stable instanced selections", async ({
		workerPage,
	}) => {
		const selections = await workerPage.evaluate(async (uri: string) => {
			await (<any>window).addGLTF(uri);
			const SDV = (<any>window).SDV;
			const viewer = (<any>window).viewer;
			const firstNode = (<any>window).findNode("box_node_3");
			const secondNode = (<any>window).findNode("box_node_4");
			const outlineA = viewer.postProcessing.addEffect({
				properties: {},
				type: SDV.POST_PROCESSING_EFFECT_TYPE.OUTLINE,
			});
			const outlineB = viewer.postProcessing.addEffect({
				properties: {},
				type: SDV.POST_PROCESSING_EFFECT_TYPE.OUTLINE,
			});
			const bloom = viewer.postProcessing.addEffect({
				properties: {},
				type: SDV.POST_PROCESSING_EFFECT_TYPE.SELECTIVE_BLOOM,
			});
			viewer.postProcessing.outlineEffects[outlineA].addSelection(
				firstNode,
			);
			viewer.postProcessing.outlineEffects[outlineB].addSelection(
				secondNode,
			);
			viewer.postProcessing.selectiveBloomEffects[bloom].addSelection(
				secondNode,
			);
			await (<any>window).rerender();

			return [outlineA, outlineB, bloom].map((token) => {
				const effect = viewer.postProcessing.getEffect(token);
				const objects = [...effect.selection];
				return {
					count: objects.length,
					inScene: objects.every(
						(object: any) => object.parent !== null,
					),
				};
			});
		}, `${ASSET_HOST}/duplicated-boxes.glb`);

		for (const selection of selections) {
			expect(selection.count).toBeGreaterThan(0);
			expect(selection.inScene).toBe(true);
		}
	});
});
