import {Page, test as base, expect} from "@playwright/test";
import * as fs from "fs";
import * as path from "path";

/**
 * GPU-instancing tests. The .glb assets are generated by
 * tests/instancing/generate-assets.js and served to the page via request
 * interception, so no external hosting is involved.
 */

const name = "instancing";
const ASSET_HOST = "https://instancing-assets.viewertests.invalid";
const assetsDir = path.join(__dirname, "assets");

const test = base.extend<{}, {workerPage: Page}>({
	workerPage: [
		async ({browser}, use) => {
			const context = await browser.newContext({
				viewport: {width: 1280, height: 720},
				deviceScaleFactor: 1,
			});
			const page = await context.newPage();

			// Serve the generated test assets from disk.
			await page.route(`${ASSET_HOST}/**`, async (route) => {
				const url = new URL(route.request().url());
				const assetPath = path.join(
					assetsDir,
					path.basename(url.pathname),
				);
				if (!fs.existsSync(assetPath)) {
					await route.fulfill({status: 404});
					return;
				}
				await route.fulfill({
					status: 200,
					contentType: "model/gltf-binary",
					body: fs.readFileSync(assetPath),
				});
			});

			await page.goto("test-cdn/index.html");

			await page.evaluate(async () => {
				const SDV = (<any>window).SDV;
				const DataEngine = (<any>window).SDV.DataEngine;

				const viewer = await SDV.createViewport({
					canvas: <HTMLCanvasElement>(
						document.getElementById("canvas")
					),
					id: "myViewer",
					branding: {
						backgroundColor: "rgb(3, 5, 49)",
					},
				});
				// Detection and batching are opt-in; enable before any glTF load.
				viewer.gpuInstancing.enabled = true;
				viewer.beautyRenderDelay = 100;
				viewer.beautyRenderBlendingDuration = 100;
				viewer.shadows = false;
				viewer.physicallyCorrectLights = true;
				viewer.groundPlaneVisibility = false;
				viewer.gridVisibility = false;
				viewer.environmentMap = SDV.ENVIRONMENT_MAP.NEUTRAL;
				(<any>window).viewer = viewer;

				await new Promise<void>((resolve) => {
					SDV.addListener(SDV.EVENTTYPE.TASK.TASK_END, (e: any) => {
						if (e.type === SDV.TASK_TYPE.ENVIRONMENT_MAP_LOADING)
							resolve();
					});
				});

				const renderedP = () =>
					new Promise<void>((resolve) => {
						SDV.addListener(
							SDV.EVENTTYPE.RENDERING.BEAUTY_RENDERING_FINISHED,
							() => resolve(),
						);
					});

				let currentNode: any;
				(<any>window).addGLTF = async (uri: string) => {
					const node = await DataEngine.instance.loadContent({
						format: "gltf",
						href: uri,
					});
					const renderingP = renderedP();
					if (currentNode) SDV.sceneTree.removeNode(currentNode);
					currentNode = node;
					SDV.sceneTree.addNode(currentNode);
					SDV.sceneTree.root.updateVersion();
					viewer.show = true;
					await renderingP;
					await viewer.camera!.zoomTo(undefined, {duration: 0});
					await new Promise<void>((resolve) => {
						SDV.addListener(
							SDV.EVENTTYPE.RENDERING.BEAUTY_RENDERING_FINISHED,
							() => resolve(),
						);
						viewer.render();
					});
				};

				/** Renders and waits for the beauty pass. */
				(<any>window).rerender = async () => {
					SDV.sceneTree.root.updateVersion();
					await new Promise<void>((resolve) => {
						SDV.addListener(
							SDV.EVENTTYPE.RENDERING.BEAUTY_RENDERING_FINISHED,
							() => resolve(),
						);
						viewer.render();
					});
				};

				/** Finds a tree node by name (depth-first). */
				(<any>window).findNode = (nodeName: string) => {
					const search = (node: any): any => {
						if (node.name === nodeName) return node;
						for (const child of node.children) {
							const found = search(child);
							if (found) return found;
						}
						return undefined;
					};
					return search(SDV.sceneTree.root);
				};
			});

			await use(page);
			await context.close();
		},
		{scope: "worker"},
	],
});

test.describe("GPU instancing", () => {
	test.describe.configure({mode: "serial"});

	test("duplicated meshes are batched with per-instance colors", async ({
		workerPage,
	}) => {
		await workerPage.evaluate(async (uri: string) => {
			await (<any>window).addGLTF(uri);
		}, `${ASSET_HOST}/duplicated-boxes.glb`);

		// 9 opaque duplicated boxes → one group; the tetrahedron (unique) and
		// the 2 transparent boxes are excluded.
		const stats = await workerPage.evaluate(
			() => (<any>window).viewer.gpuInstancing.stats,
		);
		expect(stats.groupCount).toBe(1);
		expect(stats.instanceCount).toBe(9);

		await expect(workerPage).toHaveScreenshot(
			name + "/duplicated-boxes.png",
			{animations: "allow"},
		);
	});

	test("hiding one node hides only its instance", async ({workerPage}) => {
		await workerPage.evaluate(async () => {
			const node = (<any>window).findNode("box_node_4");
			node.visible = false;
			await (<any>window).rerender();
		});

		const stats = await workerPage.evaluate(
			() => (<any>window).viewer.gpuInstancing.stats,
		);
		expect(stats.instanceCount).toBe(9);

		await expect(workerPage).toHaveScreenshot(
			name + "/duplicated-boxes-hidden-instance.png",
			{animations: "allow"},
		);

		await workerPage.evaluate(async () => {
			const node = (<any>window).findNode("box_node_4");
			node.visible = true;
			await (<any>window).rerender();
		});
	});

	test("interaction material highlights only one instance", async ({
		workerPage,
	}) => {
		await workerPage.evaluate(async () => {
			const SDV = (<any>window).SDV;
			const node = (<any>window).findNode("box_node_4");
			const geometryData = node.data.find(
				(d: any) => d.instanceHash !== undefined,
			);
			geometryData.effectMaterials.push({
				material: new SDV.MaterialStandardData({color: "#ff00ff"}),
				token: "test-highlight",
			});
			(<any>window).viewer.updateGeometryData(geometryData);
			await (<any>window).rerender();
		});

		await expect(workerPage).toHaveScreenshot(
			name + "/duplicated-boxes-highlight.png",
			{animations: "allow"},
		);

		// Remove the highlight again; the instance returns to its batch.
		await workerPage.evaluate(async () => {
			const node = (<any>window).findNode("box_node_4");
			const geometryData = node.data.find(
				(d: any) => d.instanceHash !== undefined,
			);
			geometryData.effectMaterials.pop();
			(<any>window).viewer.updateGeometryData(geometryData);
			await (<any>window).rerender();
		});
		const stats = await workerPage.evaluate(
			() => (<any>window).viewer.gpuInstancing.stats,
		);
		expect(stats.effectMeshCount).toBe(0);

		await expect(workerPage).toHaveScreenshot(
			name + "/duplicated-boxes.png",
			{animations: "allow"},
		);
	});

	test("a mesh shared by several nodes is batched", async ({workerPage}) => {
		await workerPage.evaluate(async (uri: string) => {
			await (<any>window).addGLTF(uri);
		}, `${ASSET_HOST}/shared-mesh-boxes.glb`);

		const stats = await workerPage.evaluate(
			() => (<any>window).viewer.gpuInstancing.stats,
		);
		expect(stats.groupCount).toBe(1);
		expect(stats.instanceCount).toBe(9);

		await expect(workerPage).toHaveScreenshot(
			name + "/shared-mesh-boxes.png",
			{animations: "allow"},
		);
	});

	test("baked transforms are extracted into instances", async ({
		workerPage,
	}) => {
		await workerPage.evaluate(async (uri: string) => {
			await (<any>window).addGLTF(uri);
		}, `${ASSET_HOST}/baked-boxes.glb`);

		const stats = await workerPage.evaluate(
			() => (<any>window).viewer.gpuInstancing.stats,
		);
		expect(stats.groupCount).toBe(1);
		expect(stats.instanceCount).toBe(6);

		await expect(workerPage).toHaveScreenshot(name + "/baked-boxes.png", {
			animations: "allow",
		});
	});

	test("disabling instancing falls back to regular meshes", async ({
		workerPage,
	}) => {
		await workerPage.evaluate(async (uri: string) => {
			(<any>window).viewer.gpuInstancing.enabled = false;
			await (<any>window).addGLTF(uri);
		}, `${ASSET_HOST}/duplicated-boxes.glb`);

		const stats = await workerPage.evaluate(
			() => (<any>window).viewer.gpuInstancing.stats,
		);
		expect(stats.groupCount).toBe(0);

		await expect(workerPage).toHaveScreenshot(
			name + "/duplicated-boxes.png",
			{animations: "allow"},
		);

		await workerPage.evaluate(() => {
			(<any>window).viewer.gpuInstancing.enabled = true;
		});
	});
});
