import {
	type IAnchor,
	type ITag2D,
	type ITag3D,
	TAG3D_JUSTIFICATION} from "./anchor/interfaces";
import {
	ACCESSORCOMPONENTSIZE as ACCESSORCOMPONENTSIZE_V1,
	ACCESSORCOMPONENTTYPE as ACCESSORCOMPONENTTYPE_V1,
	ACCESSORTYPE as ACCESSORTYPE_V1,
	type IGLTF_v1,
	type IGLTF_v1_Accessor,
	type IGLTF_v1_Animation,
	type IGLTF_v1_Asset,
	type IGLTF_v1_Buffer,
	type IGLTF_v1_BufferView,
	type IGLTF_v1_Camera,
	type IGLTF_v1_Image,
	type IGLTF_v1_Material,
	type IGLTF_v1_Mesh,
	type IGLTF_v1_Node,
	type IGLTF_v1_Program,
	type IGLTF_v1_Sampler,
	type IGLTF_v1_Scene,
	type IGLTF_v1_Shader,
	type IGLTF_v1_Skin,
	type IGLTF_v1_Technique,
	type IGLTF_v1_Texture} from "./gltfv1/IGLTF_v1";
import {type ISDGTF_v1} from "./gltfv1/ISDGTF_v1";
import {
	ACCESSORCOMPONENTSIZE as ACCESSORCOMPONENTSIZE_V2,
	ACCESSORCOMPONENTTYPE as ACCESSORCOMPONENTTYPE_V2,
	ACCESSORTYPE as ACCESSORTYPE_V2,
	type IGLTF_v2,
	type IGLTF_v2_Accessor,
	type IGLTF_v2_Animation,
	type IGLTF_v2_Asset,
	type IGLTF_v2_Buffer,
	type IGLTF_v2_BufferView,
	type IGLTF_v2_Camera,
	type IGLTF_v2_Image,
	type IGLTF_v2_Material,
	type IGLTF_v2_Material_KHR_materials_pbrSpecularGlossiness,
	type IGLTF_v2_Mesh,
	type IGLTF_v2_Node,
	type IGLTF_v2_Primitive,
	type IGLTF_v2_Sampler,
	type IGLTF_v2_Scene,
	type IGLTF_v2_Skin,
	type IGLTF_v2_Texture,
	type ISHAPEDIVER_materials_preset} from "./gltfv2/IGLTF_v2";
import {
	type IMaterialContentData,
	type IMaterialContentDataV1,
	type IMaterialContentDataV2,
	type IMaterialContentDataV3,
	type IPresetMaterialDefinition,
	type ITexture} from "./material/interfaces";
import {
	type ISDTF,
	type ISDTF_Accessor,
	type ISDTF_Attribute,
	type ISDTF_Buffer,
	type ISDTF_BufferView,
	type ISDTF_Chunk,
	type ISDTF_Item,
	type ISDTF_Node,
	type ISDTF_TypeHint} from "./sdtf/ISDTF";

export {
	ACCESSORCOMPONENTSIZE_V1,
	ACCESSORCOMPONENTSIZE_V2,
	ACCESSORCOMPONENTTYPE_V1,
	ACCESSORCOMPONENTTYPE_V2,
	ACCESSORTYPE_V1,
	ACCESSORTYPE_V2,
	TAG3D_JUSTIFICATION,
};
export type {
	IAnchor,
	IGLTF_v1,
	IGLTF_v1_Accessor,
	IGLTF_v1_Animation,
	IGLTF_v1_Asset,
	IGLTF_v1_Buffer,
	IGLTF_v1_BufferView,
	IGLTF_v1_Camera,
	IGLTF_v1_Image,
	IGLTF_v1_Material,
	IGLTF_v1_Mesh,
	IGLTF_v1_Node,
	IGLTF_v1_Program,
	IGLTF_v1_Sampler,
	IGLTF_v1_Scene,
	IGLTF_v1_Shader,
	IGLTF_v1_Skin,
	IGLTF_v1_Technique,
	IGLTF_v1_Texture,
	IGLTF_v2,
	IGLTF_v2_Accessor,
	IGLTF_v2_Animation,
	IGLTF_v2_Asset,
	IGLTF_v2_Buffer,
	IGLTF_v2_BufferView,
	IGLTF_v2_Camera,
	IGLTF_v2_Image,
	IGLTF_v2_Material,
	IGLTF_v2_Material_KHR_materials_pbrSpecularGlossiness,
	IGLTF_v2_Mesh,
	IGLTF_v2_Node,
	IGLTF_v2_Primitive,
	IGLTF_v2_Sampler,
	IGLTF_v2_Scene,
	IGLTF_v2_Skin,
	IGLTF_v2_Texture,
	IMaterialContentData,
	IMaterialContentDataV1,
	IMaterialContentDataV2,
	IMaterialContentDataV3,
	IPresetMaterialDefinition,
	ISDGTF_v1,
	ISDTF,
	ISDTF_Accessor,
	ISDTF_Attribute,
	ISDTF_Buffer,
	ISDTF_BufferView,
	ISDTF_Chunk,
	ISDTF_Item,
	ISDTF_Node,
	ISDTF_TypeHint,
	ISHAPEDIVER_materials_preset,
	ITag2D,
	ITag3D,
	ITexture,
};
