import {
	ResExportDefinitionType as EXPORT_TYPE,
	ResExport as ShapeDiverResponseExport,
	ResExportContent as ShapeDiverResponseExportContent,
	ReqExportDefinitionGroup as ShapeDiverResponseExportDefinitionGroup,
	ResExportResult as ShapeDiverResponseExportResult,
	ResModelComputationStats as ShapeDiverResponseModelComputationStatus,
	ResOutput as ShapeDiverResponseOutput,
	ResOutputChunk as ShapeDiverResponseOutputChunkBackend,
	ResOutputContent as ShapeDiverResponseOutputContentBackend,
	ResParameter as ShapeDiverResponseParameter,
} from "@shapediver/sdk.geometry-api-sdk-v2";
import {
	addListener,
	generalOptions,
	type IGeneralOptions,
	removeListener,
	sceneTree,
	version} from "@shapediver/viewer.api.general";
import {
	type IMaterialContentDataV1,
	type IMaterialContentDataV2,
	type IMaterialContentDataV3,
	type ITag2D,
	type ITag3D,
	type ITexture,
	TAG3D_JUSTIFICATION} from "@shapediver/viewer.data-engine.shared-types";
import {
	type ISessionData,
	type ISessionOutputData,
	SessionData,
	SessionOutputData,
	type ResOutputChunk as ShapeDiverResponseOutputChunk,
	type ResOutputContent as ShapeDiverResponseOutputContent} from "@shapediver/viewer.session-engine.session-engine";
import {
	Box,
	type IBox,
	type IGeometry,
	type ISphere,
	Sphere} from "@shapediver/viewer.shared.math";
import {
	AnimationData,
	AttributeData,
	ChunkData,
	CustomData,
	GeometryData,
	HTMLElementAnchorCustomData,
	HTMLElementAnchorData,
	HTMLElementAnchorImageData,
	HTMLElementAnchorTextData,
	InstanceData,
	type ITransformation,
	type ITree,
	type ITreeNode,
	type ITreeNodeData,
	MapData,
	MaterialBasicLineData,
	MaterialGemData,
	MaterialLambertData,
	MaterialMultiPointData,
	MaterialPhongData,
	MaterialPointData,
	MaterialShadowData,
	MaterialSpecularGlossinessData,
	MaterialStandardData,
	MaterialUnlitData,
	MaterialVariantsData,
	PrimitiveData,
	SDTFAttributeData,
	SDTFAttributesData,
	SDTFItemData,
	SDTFOverviewData,
	Tree,
	TreeNode} from "@shapediver/viewer.shared.node-tree";
import {
	Converter,
	defaultSettings,
	EVENTTYPE,
	EVENTTYPE_CAMERA,
	EVENTTYPE_DRAWING_TOOLS,
	EVENTTYPE_INTERACTION,
	EVENTTYPE_OUTPUT,
	EVENTTYPE_PARAMETER,
	EVENTTYPE_RENDERING,
	EVENTTYPE_SCENE,
	EVENTTYPE_SESSION,
	EVENTTYPE_TASK,
	EVENTTYPE_TRANSFORMATION_TOOLS,
	EVENTTYPE_VIEWPORT,
	type IDomEventListener,
	type IEvent,
	isARError,
	isValid,
	isViewerCameraError,
	isViewerCustomizationError,
	isViewerDataProcessingError,
	isViewerDrawingToolsError,
	isViewerEnvironmentMapError,
	isViewerError,
	isViewerGeometryBackendError,
	isViewerGeometryBackendGenericError,
	isViewerGeometryBackendRequestError,
	isViewerGeometryBackendResponseError,
	isViewerInteractionError,
	isViewerLightError,
	isViewerSessionError,
	isViewerSettingsError,
	isViewerUnknownError,
	isViewerValidationError,
	isViewerViewportError,
	isViewerWebGLError,
	LOGGING_LEVEL,
	type MainEventTypes,
	SESSION_SETTINGS_MODE,
	ShapeDiverGeometryBackendError,
	ShapeDiverGeometryBackendRequestError,
	ShapeDiverGeometryBackendResponseError,
	ShapeDiverGeometryBackendResponseErrorType,
	ShapeDiverViewerArError,
	ShapeDiverViewerCameraError,
	ShapeDiverViewerCustomizationError,
	ShapeDiverViewerDataProcessingError,
	ShapeDiverViewerDrawingToolsError,
	ShapeDiverViewerEnvironmentMapError,
	ShapeDiverViewerError,
	ShapeDiverViewerErrorType,
	ShapeDiverViewerInteractionError,
	ShapeDiverViewerLightError,
	ShapeDiverViewerSessionError,
	ShapeDiverViewerSettingsError,
	ShapeDiverViewerUnknownError,
	ShapeDiverViewerValidationError,
	ShapeDiverViewerViewportError,
	ShapeDiverViewerWebGLError,
	stringify,
	SystemInfo} from "@shapediver/viewer.shared.services";
import {
	BUSY_MODE_DISPLAY,
	type DraggingParameterValue,
	type DrawingParameterValue,
	type EventResponseMapping,
	FLAG_TYPE,
	type GumballTransformParameterValue,
	type IAnchorDataImage,
	type IAnchorDataText,
	type IAnimationData,
	type IAnimationTrack,
	type IAttributeData,
	type ICameraEvent,
	type IChunkData,
	type ICustomData,
	IDraggingParameterJsonSchema,
	type IDraggingParameterProps,
	IDraggingParameterPropsJsonSchema,
	IDrawingParameterJsonSchema,
	type IDrawingParameterSettings,
	type IGeometryData,
	IGumballTransformParameterJsonSchema,
	type IGumballTransformParameterProps,
	IGumballTransformParameterPropsJsonSchema,
	type IHTMLElementAnchorData,
	type IHTMLElementAnchorUpdateProperties,
	type IInstanceData,
	IInteractionParameterJsonSchema,
	type IInteractionParameterProps,
	type IInteractionParameterSettings,
	type IMapData,
	type IMapDataProperties,
	type IMapDataPropertiesDefinition,
	type IMaterialAbstractData,
	type IMaterialAbstractDataProperties,
	type IMaterialAbstractDataPropertiesDefinition,
	type IMaterialBasicLineData,
	type IMaterialBasicLineDataProperties,
	type IMaterialBasicLineDataPropertiesDefinition,
	type IMaterialGemData,
	type IMaterialGemDataProperties,
	type IMaterialGemDataPropertiesDefinition,
	type IMaterialLambertData,
	type IMaterialLambertDataProperties,
	type IMaterialLambertDataPropertiesDefinition,
	type IMaterialMultiPointData,
	type IMaterialMultiPointDataProperties,
	type IMaterialMultiPointDataPropertiesDefinition,
	type IMaterialPhongData,
	type IMaterialPhongDataProperties,
	type IMaterialPhongDataPropertiesDefinition,
	type IMaterialPointData,
	type IMaterialPointDataProperties,
	type IMaterialPointDataPropertiesDefinition,
	type IMaterialShadowData,
	type IMaterialShadowDataProperties,
	type IMaterialShadowDataPropertiesDefinition,
	type IMaterialSpecularGlossinessData,
	type IMaterialSpecularGlossinessDataProperties,
	type IMaterialSpecularGlossinessDataPropertiesDefinition,
	type IMaterialStandardData,
	type IMaterialStandardDataProperties,
	type IMaterialStandardDataPropertiesDefinition,
	type IMaterialUnlitData,
	type IMaterialUnlitDataProperties,
	type IMaterialUnlitDataPropertiesDefinition,
	type IMaterialVariantsData,
	type InteractionParameterSettingsType,
	type IOutputEvent,
	type IParameterEvent,
	type IPrimitiveData,
	IRectangleTransformParameterJsonSchema,
	type IRectangleTransformParameterProps,
	IRectangleTransformParameterPropsJsonSchema,
	type IRenderingEvent,
	type ISceneEvent,
	type ISDTFAttributeData,
	type ISDTFAttributesData,
	type ISDTFAttributeVisualizationData,
	type ISDTFItemData,
	type ISDTFOverview,
	type ISDTFOverviewData,
	ISelectionParameterJsonSchema,
	type ISelectionParameterProps,
	ISelectionParameterPropsJsonSchema,
	type ISessionErrorEvent,
	type ISessionEvent,
	type ISessionSettingsSections,
	type ISettingsSections,
	type ITaskEvent,
	type ITaskEventDescription,
	type IViewportEvent,
	type IViewportSettingsSections,
	ENVIRONMENT_MAP_PBR_MODE,
	MATERIAL_ALPHA,
	MATERIAL_SHADING,
	MATERIAL_SIDE,
	MATERIAL_TYPE,
	PARAMETER_TYPE,
	PARAMETER_VISUALIZATION,
	PRIMITIVE_MODE,
	type RectangleTransformParameterValue,
	RENDERER_TYPE,
	SDTF_TYPEHINT,
	SdtfPrimitiveTypeGuard,
	type SelectionParameterValue,
	type SessionCreationDefinition,
	SPINNER_POSITIONING,
	TASK_CATEGORY,
	TASK_CATEGORY_SESSION_CUSTOMIZATION_CATEGORY,
	TASK_TYPE,
	type TaskCategoryTypes,
	TEXTURE_ENCODING,
	TEXTURE_FILTERING,
	TEXTURE_WRAPPING,
	TONE_MAPPING,
	validateDraggingParameterSettings,
	validateDrawingParameterSettings,
	validateGumballTransformParameterSettings,
	validateInteractionParameterSettings,
	validateRectangleTransformParameterSettings,
	validateSelectionParameterSettings,
	type ViewportCreationDefinition,
	VISIBILITY_MODE} from "@shapediver/viewer.shared.types";
import {OutputApiData} from "./implementation/data/OutputApiData";
import {SessionApiData} from "./implementation/data/SessionApiData";
import {isExportApi} from "./implementation/ExportApi";
import {isOutputApi} from "./implementation/OutputApi";
import {isDraggingParameterApi} from "./implementation/parameter/DraggingParameterApi";
import {isDrawingParameterApi} from "./implementation/parameter/DrawingParameterApi";
import {isFileParameterApi} from "./implementation/parameter/FileParameterApi";
import {isGumballTransformParameterApi} from "./implementation/parameter/GumballTransformParameterApi";
import {isParameterApi} from "./implementation/parameter/ParameterApi";
import {isRectangleTransformParameterApi} from "./implementation/parameter/RectangleTransformParameterApi";
import {isSelectionParameterApi} from "./implementation/parameter/SelectionParameterApi";
import {isSessionApi} from "./implementation/SessionApi";
import {type IOutputApiData} from "./interfaces/data/IOutputApiData";
import {type ISessionApiData} from "./interfaces/data/ISessionApiData";
import {type IExportApi} from "./interfaces/IExportApi";
import {type IOutputApi} from "./interfaces/IOutputApi";
import {type ISessionApi} from "./interfaces/ISessionApi";
import {type IDraggingParameterApi} from "./interfaces/parameter/IDraggingParameterApi";
import {type IDrawingParameterApi} from "./interfaces/parameter/IDrawingParameterApi";
import {type IFileParameterApi} from "./interfaces/parameter/IFileParameterApi";
import {type IGumballTransformParameterApi} from "./interfaces/parameter/IGumballTransformParameterApi";
import {type IParameterApi} from "./interfaces/parameter/IParameterApi";
import {type IRectangleTransformParameterApi} from "./interfaces/parameter/IRectangleTransformParameterApi";
import {type ISelectionParameterApi} from "./interfaces/parameter/ISelectionParameterApi";
import {createSession, sessions} from "./main";

export {addListener,
	AnimationData,
	AttributeData,
	Box,
	BUSY_MODE_DISPLAY,
	ChunkData,
	Converter,
	createSession,
	CustomData,
	defaultSettings,
	EVENTTYPE,
	EVENTTYPE_CAMERA,
	EVENTTYPE_DRAWING_TOOLS,
	EVENTTYPE_INTERACTION,
	EVENTTYPE_OUTPUT,
	EVENTTYPE_PARAMETER,
	EVENTTYPE_RENDERING,
	EVENTTYPE_SCENE,
	EVENTTYPE_SESSION,
	EVENTTYPE_TASK,
	EVENTTYPE_TRANSFORMATION_TOOLS,
	EVENTTYPE_VIEWPORT,
	EXPORT_TYPE,
	FLAG_TYPE,
	generalOptions,
	GeometryData,
	HTMLElementAnchorCustomData,
	HTMLElementAnchorData,
	HTMLElementAnchorImageData,
	HTMLElementAnchorTextData,
	IDraggingParameterJsonSchema,
	IDraggingParameterPropsJsonSchema,
	IDrawingParameterJsonSchema,
	IGumballTransformParameterJsonSchema,
	IGumballTransformParameterPropsJsonSchema,
	IInteractionParameterJsonSchema,
	InstanceData,
	IRectangleTransformParameterJsonSchema,
	IRectangleTransformParameterPropsJsonSchema,
	isARError,
	isDraggingParameterApi,
	isDrawingParameterApi,
	ISelectionParameterJsonSchema,
	ISelectionParameterPropsJsonSchema,
	isExportApi,
	isFileParameterApi,
	isGumballTransformParameterApi,
	isOutputApi,
	isParameterApi,
	isRectangleTransformParameterApi,
	isSelectionParameterApi,
	isSessionApi,
	isValid,
	isViewerCameraError,
	isViewerCustomizationError,
	isViewerDataProcessingError,
	isViewerDrawingToolsError,
	isViewerEnvironmentMapError,
	isViewerError,
	isViewerGeometryBackendError,
	isViewerGeometryBackendGenericError,
	isViewerGeometryBackendRequestError,
	isViewerGeometryBackendResponseError,
	isViewerInteractionError,
	isViewerLightError,
	isViewerSessionError,
	isViewerSettingsError,
	isViewerUnknownError,
	isViewerValidationError,
	isViewerViewportError,
	isViewerWebGLError,
	LOGGING_LEVEL,
	MapData,
	ENVIRONMENT_MAP_PBR_MODE,
	MATERIAL_ALPHA,
	MATERIAL_SHADING,
	MATERIAL_SIDE,
	MATERIAL_TYPE,
	MaterialBasicLineData,
	MaterialGemData,
	MaterialLambertData,
	MaterialMultiPointData,
	MaterialPhongData,
	MaterialPointData,
	MaterialShadowData,
	MaterialSpecularGlossinessData,
	MaterialStandardData,
	MaterialUnlitData,
	MaterialVariantsData,
	OutputApiData,
	PARAMETER_TYPE,
	PARAMETER_VISUALIZATION,
	PRIMITIVE_MODE,
	PrimitiveData,
	removeListener,
	RENDERER_TYPE,
	sceneTree,
	SDTF_TYPEHINT,
	SDTFAttributeData,
	SDTFAttributesData,
	SDTFItemData,
	SDTFOverviewData,
	SdtfPrimitiveTypeGuard,
	SESSION_SETTINGS_MODE,
	SessionApiData,
	SessionData,
	SessionOutputData,
	sessions,
	ShapeDiverGeometryBackendError,
	ShapeDiverGeometryBackendRequestError,
	ShapeDiverGeometryBackendResponseError,
	ShapeDiverGeometryBackendResponseErrorType,
	ShapeDiverResponseExport,
	ShapeDiverResponseExportContent,
	ShapeDiverResponseExportDefinitionGroup,
	ShapeDiverResponseExportResult,
	ShapeDiverResponseModelComputationStatus,
	ShapeDiverResponseOutput,
	ShapeDiverResponseOutputChunkBackend,
	ShapeDiverResponseOutputContentBackend,
	ShapeDiverResponseParameter,
	ShapeDiverViewerArError,
	ShapeDiverViewerCameraError,
	ShapeDiverViewerCustomizationError,
	ShapeDiverViewerDataProcessingError,
	ShapeDiverViewerDrawingToolsError,
	ShapeDiverViewerEnvironmentMapError,
	ShapeDiverViewerError,
	ShapeDiverViewerErrorType,
	ShapeDiverViewerInteractionError,
	ShapeDiverViewerLightError,
	ShapeDiverViewerSessionError,
	ShapeDiverViewerSettingsError,
	ShapeDiverViewerUnknownError,
	ShapeDiverViewerValidationError,
	ShapeDiverViewerViewportError,
	ShapeDiverViewerWebGLError,
	Sphere,
	SPINNER_POSITIONING,
	stringify,
	SystemInfo,
	TAG3D_JUSTIFICATION,
	TASK_CATEGORY,
	TASK_CATEGORY_SESSION_CUSTOMIZATION_CATEGORY,
	TASK_TYPE,
	TEXTURE_ENCODING,
	TEXTURE_FILTERING,
	TEXTURE_WRAPPING,
	TONE_MAPPING,
	Tree,
	TreeNode,
	validateDraggingParameterSettings,
	validateDrawingParameterSettings,
	validateGumballTransformParameterSettings,
	validateInteractionParameterSettings,
	validateRectangleTransformParameterSettings,
	validateSelectionParameterSettings,
	version,
	VISIBILITY_MODE};
export type {DraggingParameterValue,
	DrawingParameterValue,
	EventResponseMapping,
	GumballTransformParameterValue,
	IAnchorDataImage,
	IAnchorDataText,
	IAnimationData,
	IAnimationTrack,
	IAttributeData,
	IBox,
	ICameraEvent,
	IChunkData,
	ICustomData,
	IDomEventListener,
	IDraggingParameterApi,
	IDraggingParameterProps,
	IDrawingParameterApi,
	IDrawingParameterSettings,
	IEvent,
	IExportApi,
	IFileParameterApi,
	IGeneralOptions,
	IGeometry,
	IGeometryData,
	IGumballTransformParameterApi,
	IGumballTransformParameterProps,
	IHTMLElementAnchorData,
	IHTMLElementAnchorUpdateProperties,
	IInstanceData,
	IInteractionParameterProps,
	IInteractionParameterSettings,
	IMapData,
	IMapDataProperties,
	IMapDataPropertiesDefinition,
	IMaterialAbstractData,
	IMaterialAbstractDataProperties,
	IMaterialAbstractDataPropertiesDefinition,
	IMaterialBasicLineData,
	IMaterialBasicLineDataProperties,
	IMaterialBasicLineDataPropertiesDefinition,
	IMaterialContentDataV1,
	IMaterialContentDataV2,
	IMaterialContentDataV3,
	IMaterialGemData,
	IMaterialGemDataProperties,
	IMaterialGemDataPropertiesDefinition,
	IMaterialLambertData,
	IMaterialLambertDataProperties,
	IMaterialLambertDataPropertiesDefinition,
	IMaterialMultiPointData,
	IMaterialMultiPointDataProperties,
	IMaterialMultiPointDataPropertiesDefinition,
	IMaterialPhongData,
	IMaterialPhongDataProperties,
	IMaterialPhongDataPropertiesDefinition,
	IMaterialPointData,
	IMaterialPointDataProperties,
	IMaterialPointDataPropertiesDefinition,
	IMaterialShadowData,
	IMaterialShadowDataProperties,
	IMaterialShadowDataPropertiesDefinition,
	IMaterialSpecularGlossinessData,
	IMaterialSpecularGlossinessDataProperties,
	IMaterialSpecularGlossinessDataPropertiesDefinition,
	IMaterialStandardData,
	IMaterialStandardDataProperties,
	IMaterialStandardDataPropertiesDefinition,
	IMaterialUnlitData,
	IMaterialUnlitDataProperties,
	IMaterialUnlitDataPropertiesDefinition,
	IMaterialVariantsData,
	InteractionParameterSettingsType,
	IOutputApi,
	IOutputApiData,
	IOutputEvent,
	IParameterApi,
	IParameterEvent,
	IPrimitiveData,
	IRectangleTransformParameterApi,
	IRectangleTransformParameterProps,
	IRenderingEvent,
	ISceneEvent,
	ISDTFAttributeData,
	ISDTFAttributesData,
	ISDTFAttributeVisualizationData,
	ISDTFItemData,
	ISDTFOverview,
	ISDTFOverviewData,
	ISelectionParameterApi,
	ISelectionParameterProps,
	ISessionApi,
	ISessionApiData,
	ISessionData,
	ISessionErrorEvent,
	ISessionEvent,
	ISessionOutputData,
	ISessionSettingsSections,
	ISettingsSections,
	ISphere,
	ITag2D,
	ITag3D,
	ITaskEvent,
	ITaskEventDescription,
	ITexture,
	ITransformation,
	ITree,
	ITreeNode,
	ITreeNodeData,
	IViewportEvent,
	IViewportSettingsSections,
	MainEventTypes,
	RectangleTransformParameterValue,
	SelectionParameterValue,
	SessionCreationDefinition,
	ShapeDiverResponseOutputChunk,
	ShapeDiverResponseOutputContent,
	TaskCategoryTypes,
	ViewportCreationDefinition};
