import {
	ResExportDefinitionType as EXPORT_TYPE,
	ResExport as ShapeDiverResponseExport,
	ResExportContent as ShapeDiverResponseExportContent,
	ReqExportDefinitionGroup as ShapeDiverResponseExportDefinitionGroup,
	ResExportResult as ShapeDiverResponseExportResult,
	ResModelComputationStats as ShapeDiverResponseModelComputationStatus,
	ResOutput as ShapeDiverResponseOutput,
	ResOutputChunk as ShapeDiverResponseOutputChunkBackend,
	ResOutputContent as ShapeDiverResponseOutputContentBackend,
	ResParameter as ShapeDiverResponseParameter,
} from "@shapediver/sdk.geometry-api-sdk-v2";
import {
	addListener,
	generalOptions,
	IGeneralOptions,
	removeListener,
	sceneTree,
	version,
} from "@shapediver/viewer.api.general";
import {DataEngine} from "@shapediver/viewer.data-engine.data-engine";
import {GeometryEngine} from "@shapediver/viewer.data-engine.geometry-engine";
import {MaterialEngine} from "@shapediver/viewer.data-engine.material-engine";
import {
	IAnchor,
	IMaterialContentData,
	IMaterialContentDataV1,
	IMaterialContentDataV2,
	IMaterialContentDataV3,
	ITag2D,
	ITag3D,
	ITexture,
	TAG3D_JUSTIFICATION,
} from "@shapediver/viewer.data-engine.shared-types";
import {
	CAMERA_TYPE,
	ICameraOptions,
	ORTHOGRAPHIC_CAMERA_DIRECTION,
	OrthographicCameraProperties,
	PerspectiveCameraProperties,
} from "@shapediver/viewer.rendering-engine.camera-engine";
import {LIGHT_TYPE} from "@shapediver/viewer.rendering-engine.light-engine";
import {
	BlendFunction,
	BloomEffect,
	ChromaticAberrationEffect,
	DepthOfFieldEffect,
	DotScreenEffect,
	Effect,
	EffectComposer,
	ENVIRONMENT_MAP,
	ENVIRONMENT_MAP_CUBE,
	ENVIRONMENT_MAP_EMPTY,
	GodRaysEffect,
	GridEffect,
	HueSaturationEffect,
	IThreejsData,
	KernelSize,
	NoiseEffect,
	OutlineEffect,
	PixelationEffect,
	Resolution,
	ScanlineEffect,
	SelectiveBloomEffect,
	SepiaEffect,
	SSAOEffect,
	ThreejsData,
	TiltShiftEffect,
	VignetteEffect,
	VignetteTechnique,
} from "@shapediver/viewer.rendering-engine.rendering-engine-threejs";
import {
	Box,
	IBox,
	IGeometry,
	ISphere,
	Sphere,
} from "@shapediver/viewer.shared.math";
import {
	AnimationData,
	AttributeData,
	ChunkData,
	CustomData,
	GeometryData,
	HTMLElementAnchorCustomData,
	HTMLElementAnchorData,
	HTMLElementAnchorImageData,
	HTMLElementAnchorTextData,
	InstanceData,
	ITransformation,
	ITree,
	ITreeNode,
	ITreeNodeData,
	MapData,
	MaterialBasicLineData,
	MaterialGemData,
	MaterialLambertData,
	MaterialMultiPointData,
	MaterialPhongData,
	MaterialPointData,
	MaterialShadowData,
	MaterialSpecularGlossinessData,
	MaterialStandardData,
	MaterialUnlitData,
	MaterialVariantsData,
	PrimitiveData,
	SDTFAttributeData,
	SDTFAttributesData,
	SDTFItemData,
	SDTFOverviewData,
	Tree,
	TreeNode,
} from "@shapediver/viewer.shared.node-tree";
import {
	Converter,
	defaultSettings,
	EVENTTYPE,
	EVENTTYPE_CAMERA,
	EVENTTYPE_DRAWING_TOOLS,
	EVENTTYPE_INTERACTION,
	EVENTTYPE_OUTPUT,
	EVENTTYPE_PARAMETER,
	EVENTTYPE_RENDERING,
	EVENTTYPE_SCENE,
	EVENTTYPE_SESSION,
	EVENTTYPE_TASK,
	EVENTTYPE_TRANSFORMATION_TOOLS,
	EVENTTYPE_VIEWPORT,
	IDomEventListener,
	IEvent,
	isARError,
	isValid,
	isViewerCameraError,
	isViewerCustomizationError,
	isViewerDataProcessingError,
	isViewerDrawingToolsError,
	isViewerEnvironmentMapError,
	isViewerError,
	isViewerGeometryBackendError,
	isViewerGeometryBackendGenericError,
	isViewerGeometryBackendRequestError,
	isViewerGeometryBackendResponseError,
	isViewerInteractionError,
	isViewerLightError,
	isViewerSessionError,
	isViewerSettingsError,
	isViewerUnknownError,
	isViewerValidationError,
	isViewerViewportError,
	isViewerWebGLError,
	LOGGING_LEVEL,
	MainEventTypes,
	SESSION_SETTINGS_MODE,
	ShapeDiverGeometryBackendError,
	ShapeDiverGeometryBackendRequestError,
	ShapeDiverGeometryBackendResponseError,
	ShapeDiverGeometryBackendResponseErrorType,
	ShapeDiverViewerArError,
	ShapeDiverViewerCameraError,
	ShapeDiverViewerCustomizationError,
	ShapeDiverViewerDataProcessingError,
	ShapeDiverViewerDrawingToolsError,
	ShapeDiverViewerEnvironmentMapError,
	ShapeDiverViewerError,
	ShapeDiverViewerErrorType,
	ShapeDiverViewerInteractionError,
	ShapeDiverViewerLightError,
	ShapeDiverViewerSessionError,
	ShapeDiverViewerSettingsError,
	ShapeDiverViewerUnknownError,
	ShapeDiverViewerValidationError,
	ShapeDiverViewerViewportError,
	ShapeDiverViewerWebGLError,
	stringify,
	SystemInfo,
} from "@shapediver/viewer.shared.services";
import {
	ANTI_ALIASING_TECHNIQUE,
	BUSY_MODE_DISPLAY,
	DraggingParameterValue,
	DrawingParameterValue,
	EventResponseMapping,
	FLAG_TYPE,
	GumballTransformParameterValue,
	IAnchorDataImage,
	IAnchorDataText,
	IAnimationData,
	IAnimationTrack,
	IAttributeData,
	IBloomEffectDefinition,
	ICameraEvent,
	IChromaticAberrationEffectDefinition,
	IChunkData,
	ICustomData,
	IDepthOfFieldEffectDefinition,
	IDotScreenEffectDefinition,
	IDraggingParameterJsonSchema,
	IDraggingParameterProps,
	IDraggingParameterPropsJsonSchema,
	IDrawingParameterJsonSchema,
	IDrawingParameterSettings,
	IGeometryData,
	IGodRaysEffectDefinition,
	IGridEffectDefinition,
	IGumballTransformParameterJsonSchema,
	IGumballTransformParameterProps,
	IGumballTransformParameterPropsJsonSchema,
	IHBAOEffectDefinition,
	IHTMLElementAnchorData,
	IHTMLElementAnchorUpdateProperties,
	IHueSaturationEffectDefinition,
	IInstanceData,
	IInteractionParameterJsonSchema,
	IInteractionParameterProps,
	IInteractionParameterSettings,
	IMapData,
	IMapDataProperties,
	IMapDataPropertiesDefinition,
	IMaterialAbstractData,
	IMaterialAbstractDataProperties,
	IMaterialAbstractDataPropertiesDefinition,
	IMaterialBasicLineData,
	IMaterialBasicLineDataProperties,
	IMaterialBasicLineDataPropertiesDefinition,
	IMaterialGemData,
	IMaterialGemDataProperties,
	IMaterialGemDataPropertiesDefinition,
	IMaterialLambertData,
	IMaterialLambertDataProperties,
	IMaterialLambertDataPropertiesDefinition,
	IMaterialMultiPointData,
	IMaterialMultiPointDataProperties,
	IMaterialMultiPointDataPropertiesDefinition,
	IMaterialPhongData,
	IMaterialPhongDataProperties,
	IMaterialPhongDataPropertiesDefinition,
	IMaterialPointData,
	IMaterialPointDataProperties,
	IMaterialPointDataPropertiesDefinition,
	IMaterialShadowData,
	IMaterialShadowDataProperties,
	IMaterialShadowDataPropertiesDefinition,
	IMaterialSpecularGlossinessData,
	IMaterialSpecularGlossinessDataProperties,
	IMaterialSpecularGlossinessDataPropertiesDefinition,
	IMaterialStandardData,
	IMaterialStandardDataProperties,
	IMaterialStandardDataPropertiesDefinition,
	IMaterialUnlitData,
	IMaterialUnlitDataProperties,
	IMaterialUnlitDataPropertiesDefinition,
	IMaterialVariantsData,
	INoiseEffectDefinition,
	InteractionParameterSettingsType,
	IOutlineEffectDefinition,
	IOutputEvent,
	IParameterEvent,
	IPixelationEffectDefinition,
	IPostProcessingEffectDefinition,
	IPrimitiveData,
	IRectangleTransformParameterJsonSchema,
	IRectangleTransformParameterProps,
	IRectangleTransformParameterPropsJsonSchema,
	IRenderingEvent,
	IScanlineEffectDefinition,
	ISceneEvent,
	ISDTFAttributeData,
	ISDTFAttributesData,
	ISDTFAttributeVisualizationData,
	ISDTFItemData,
	ISDTFOverview,
	ISDTFOverviewData,
	ISelectionParameterJsonSchema,
	ISelectionParameterProps,
	ISelectionParameterPropsJsonSchema,
	ISelectiveBloomEffectDefinition,
	ISepiaEffectDefinition,
	ISessionErrorEvent,
	ISessionEvent,
	ISessionSettingsSections,
	ISettingsSections,
	ISSAOEffectDefinition,
	ITaskEvent,
	ITaskEventDescription,
	ITiltShiftEffectDefinition,
	IViewportEvent,
	IViewportSettingsSections,
	IVignetteEffectDefinition,
	MATERIAL_ALPHA,
	MATERIAL_SHADING,
	MATERIAL_SIDE,
	MATERIAL_TYPE,
	PARAMETER_TYPE,
	PARAMETER_VISUALIZATION,
	POST_PROCESSING_EFFECT_TYPE,
	PRIMITIVE_MODE,
	RectangleTransformParameterValue,
	RENDERER_TYPE,
	SDTF_TYPEHINT,
	SdtfPrimitiveTypeGuard,
	SelectionParameterValue,
	SessionCreationDefinition,
	SPINNER_POSITIONING,
	TASK_CATEGORY,
	TASK_CATEGORY_SESSION_CUSTOMIZATION_CATEGORY,
	TASK_TYPE,
	TaskCategoryTypes,
	TEXTURE_ENCODING,
	TEXTURE_FILTERING,
	TEXTURE_WRAPPING,
	TONE_MAPPING,
	validateDraggingParameterSettings,
	validateDrawingParameterSettings,
	validateGumballTransformParameterSettings,
	validateInteractionParameterSettings,
	validateRectangleTransformParameterSettings,
	validateSelectionParameterSettings,
	ViewportCreationDefinition,
	VISIBILITY_MODE,
} from "@shapediver/viewer.shared.types";
import {ICameraApi} from "./interfaces/camera/ICameraApi";
import {IOrthographicCameraApi} from "./interfaces/camera/IOrthographicCameraApi";
import {IPerspectiveCameraApi} from "./interfaces/camera/IPerspectiveCameraApi";
import {IViewportApi} from "./interfaces/IViewportApi";
import {ILightApi} from "./interfaces/lights/ILightApi";
import {ILightSceneApi} from "./interfaces/lights/ILightSceneApi";
import {IAmbientLightApi} from "./interfaces/lights/types/IAmbientLightApi";
import {IDirectionalLightApi} from "./interfaces/lights/types/IDirectionalLightApi";
import {IHemisphereLightApi} from "./interfaces/lights/types/IHemisphereLightApi";
import {IPointLightApi} from "./interfaces/lights/types/IPointLightApi";
import {ISpotLightApi} from "./interfaces/lights/types/ISpotLightApi";
import {createViewport, viewports} from "./main";

export {
	addListener,
	AnimationData,
	ANTI_ALIASING_TECHNIQUE,
	AttributeData,
	BlendFunction,
	BloomEffect,
	Box,
	BUSY_MODE_DISPLAY,
	CAMERA_TYPE,
	ChromaticAberrationEffect,
	ChunkData,
	Converter,
	createViewport,
	CustomData,
	DataEngine,
	defaultSettings,
	DepthOfFieldEffect,
	DotScreenEffect,
	Effect,
	EffectComposer,
	ENVIRONMENT_MAP,
	ENVIRONMENT_MAP_CUBE,
	ENVIRONMENT_MAP_EMPTY,
	EVENTTYPE,
	EVENTTYPE_CAMERA,
	EVENTTYPE_DRAWING_TOOLS,
	EVENTTYPE_INTERACTION,
	EVENTTYPE_OUTPUT,
	EVENTTYPE_PARAMETER,
	EVENTTYPE_RENDERING,
	EVENTTYPE_SCENE,
	EVENTTYPE_SESSION,
	EVENTTYPE_TASK,
	EVENTTYPE_TRANSFORMATION_TOOLS,
	EVENTTYPE_VIEWPORT,
	EXPORT_TYPE,
	FLAG_TYPE,
	generalOptions,
	GeometryData,
	GeometryEngine,
	GodRaysEffect,
	GridEffect,
	HTMLElementAnchorCustomData,
	HTMLElementAnchorData,
	HTMLElementAnchorImageData,
	HTMLElementAnchorTextData,
	HueSaturationEffect,
	IDraggingParameterJsonSchema,
	IDraggingParameterPropsJsonSchema,
	IDrawingParameterJsonSchema,
	IGumballTransformParameterJsonSchema,
	IGumballTransformParameterPropsJsonSchema,
	IInteractionParameterJsonSchema,
	InstanceData,
	IRectangleTransformParameterJsonSchema,
	IRectangleTransformParameterPropsJsonSchema,
	isARError,
	ISelectionParameterJsonSchema,
	ISelectionParameterPropsJsonSchema,
	isValid,
	isViewerCameraError,
	isViewerCustomizationError,
	isViewerDataProcessingError,
	isViewerDrawingToolsError,
	isViewerEnvironmentMapError,
	isViewerError,
	isViewerGeometryBackendError,
	isViewerGeometryBackendGenericError,
	isViewerGeometryBackendRequestError,
	isViewerGeometryBackendResponseError,
	isViewerInteractionError,
	isViewerLightError,
	isViewerSessionError,
	isViewerSettingsError,
	isViewerUnknownError,
	isViewerValidationError,
	isViewerViewportError,
	isViewerWebGLError,
	KernelSize,
	LIGHT_TYPE,
	LOGGING_LEVEL,
	MapData,
	MATERIAL_ALPHA,
	MATERIAL_SHADING,
	MATERIAL_SIDE,
	MATERIAL_TYPE,
	MaterialBasicLineData,
	MaterialEngine,
	MaterialGemData,
	MaterialLambertData,
	MaterialMultiPointData,
	MaterialPhongData,
	MaterialPointData,
	MaterialShadowData,
	MaterialSpecularGlossinessData,
	MaterialStandardData,
	MaterialUnlitData,
	MaterialVariantsData,
	NoiseEffect,
	ORTHOGRAPHIC_CAMERA_DIRECTION,
	OutlineEffect,
	PARAMETER_TYPE,
	PARAMETER_VISUALIZATION,
	PixelationEffect,
	POST_PROCESSING_EFFECT_TYPE,
	PRIMITIVE_MODE,
	PrimitiveData,
	removeListener,
	RENDERER_TYPE,
	Resolution,
	ScanlineEffect,
	sceneTree,
	SDTF_TYPEHINT,
	SDTFAttributeData,
	SDTFAttributesData,
	SDTFItemData,
	SDTFOverviewData,
	SdtfPrimitiveTypeGuard,
	SelectiveBloomEffect,
	SepiaEffect,
	SESSION_SETTINGS_MODE,
	ShapeDiverGeometryBackendError,
	ShapeDiverGeometryBackendRequestError,
	ShapeDiverGeometryBackendResponseError,
	ShapeDiverGeometryBackendResponseErrorType,
	ShapeDiverViewerArError,
	ShapeDiverViewerCameraError,
	ShapeDiverViewerCustomizationError,
	ShapeDiverViewerDataProcessingError,
	ShapeDiverViewerDrawingToolsError,
	ShapeDiverViewerEnvironmentMapError,
	ShapeDiverViewerError,
	ShapeDiverViewerErrorType,
	ShapeDiverViewerInteractionError,
	ShapeDiverViewerLightError,
	ShapeDiverViewerSessionError,
	ShapeDiverViewerSettingsError,
	ShapeDiverViewerUnknownError,
	ShapeDiverViewerValidationError,
	ShapeDiverViewerViewportError,
	ShapeDiverViewerWebGLError,
	Sphere,
	SPINNER_POSITIONING,
	SSAOEffect,
	stringify,
	SystemInfo,
	TAG3D_JUSTIFICATION,
	TASK_CATEGORY,
	TASK_CATEGORY_SESSION_CUSTOMIZATION_CATEGORY,
	TASK_TYPE,
	TEXTURE_ENCODING,
	TEXTURE_FILTERING,
	TEXTURE_WRAPPING,
	ThreejsData,
	TiltShiftEffect,
	TONE_MAPPING,
	Tree,
	TreeNode,
	validateDraggingParameterSettings,
	validateDrawingParameterSettings,
	validateGumballTransformParameterSettings,
	validateInteractionParameterSettings,
	validateRectangleTransformParameterSettings,
	validateSelectionParameterSettings,
	version,
	viewports,
	VignetteEffect,
	VignetteTechnique,
	VISIBILITY_MODE,
	type DraggingParameterValue,
	type DrawingParameterValue,
	type EventResponseMapping,
	type GumballTransformParameterValue,
	type IAmbientLightApi,
	type IAnchorDataImage,
	type IAnchorDataText,
	type IAnimationData,
	type IAnimationTrack,
	type IAttributeData,
	type IBloomEffectDefinition,
	type IBox,
	type ICameraApi,
	type ICameraEvent,
	type ICameraOptions,
	type IChromaticAberrationEffectDefinition,
	type IChunkData,
	type ICustomData,
	type IDepthOfFieldEffectDefinition,
	type IDirectionalLightApi,
	type IDomEventListener,
	type IDotScreenEffectDefinition,
	type IDraggingParameterProps,
	type IDrawingParameterSettings,
	type IEvent,
	type IGeneralOptions,
	type IGeometry,
	type IGeometryData,
	type IGodRaysEffectDefinition,
	type IGridEffectDefinition,
	type IGumballTransformParameterProps,
	type IHBAOEffectDefinition,
	type IHemisphereLightApi,
	type IHTMLElementAnchorData,
	type IHTMLElementAnchorUpdateProperties,
	type IHueSaturationEffectDefinition,
	type IInstanceData,
	type IInteractionParameterProps,
	type IInteractionParameterSettings,
	type ILightApi,
	type ILightSceneApi,
	type IMapData,
	type IMapDataProperties,
	type IMapDataPropertiesDefinition,
	type IMaterialAbstractData,
	type IMaterialAbstractDataProperties,
	type IMaterialAbstractDataPropertiesDefinition,
	type IMaterialBasicLineData,
	type IMaterialBasicLineDataProperties,
	type IMaterialBasicLineDataPropertiesDefinition,
	type IMaterialGemData,
	type IMaterialGemDataProperties,
	type IMaterialGemDataPropertiesDefinition,
	type IMaterialLambertData,
	type IMaterialLambertDataProperties,
	type IMaterialLambertDataPropertiesDefinition,
	type IMaterialMultiPointData,
	type IMaterialMultiPointDataProperties,
	type IMaterialMultiPointDataPropertiesDefinition,
	type IMaterialPhongData,
	type IMaterialPhongDataProperties,
	type IMaterialPhongDataPropertiesDefinition,
	type IMaterialPointData,
	type IMaterialPointDataProperties,
	type IMaterialPointDataPropertiesDefinition,
	type IMaterialShadowData,
	type IMaterialShadowDataProperties,
	type IMaterialShadowDataPropertiesDefinition,
	type IMaterialSpecularGlossinessData,
	type IMaterialSpecularGlossinessDataProperties,
	type IMaterialSpecularGlossinessDataPropertiesDefinition,
	type IMaterialStandardData,
	type IMaterialStandardDataProperties,
	type IMaterialStandardDataPropertiesDefinition,
	type IMaterialUnlitData,
	type IMaterialUnlitDataProperties,
	type IMaterialUnlitDataPropertiesDefinition,
	type IMaterialVariantsData,
	type INoiseEffectDefinition,
	type InteractionParameterSettingsType,
	type IOrthographicCameraApi,
	type IOutlineEffectDefinition,
	type IOutputEvent,
	type IParameterEvent,
	type IPerspectiveCameraApi,
	type IPixelationEffectDefinition,
	type IPointLightApi,
	type IPostProcessingEffectDefinition,
	type IPrimitiveData,
	type IRectangleTransformParameterProps,
	type IRenderingEvent,
	type IScanlineEffectDefinition,
	type ISceneEvent,
	type ISDTFAttributeData,
	type ISDTFAttributesData,
	type ISDTFAttributeVisualizationData,
	type ISDTFItemData,
	type ISDTFOverview,
	type ISDTFOverviewData,
	type ISelectionParameterProps,
	type ISelectiveBloomEffectDefinition,
	type ISepiaEffectDefinition,
	type ISessionErrorEvent,
	type ISessionEvent,
	type ISessionSettingsSections,
	type ISettingsSections,
	type ISphere,
	type ISpotLightApi,
	type ISSAOEffectDefinition,
	type ITag2D,
	type ITag3D,
	type ITaskEvent,
	type ITaskEventDescription,
	type ITexture,
	type IThreejsData,
	type ITiltShiftEffectDefinition,
	type ITransformation,
	type ITree,
	type ITreeNode,
	type ITreeNodeData,
	type IViewportApi,
	type IViewportEvent,
	type IViewportSettingsSections,
	type IVignetteEffectDefinition,
	type MainEventTypes,
	type OrthographicCameraProperties,
	type PerspectiveCameraProperties,
	type RectangleTransformParameterValue,
	type SelectionParameterValue,
	type SessionCreationDefinition,
	type ShapeDiverResponseExport,
	type ShapeDiverResponseExportContent,
	type ShapeDiverResponseExportDefinitionGroup,
	type ShapeDiverResponseExportResult,
	type ShapeDiverResponseModelComputationStatus,
	type ShapeDiverResponseOutput,
	type ShapeDiverResponseOutputChunkBackend,
	type ShapeDiverResponseOutputContentBackend,
	type ShapeDiverResponseParameter,
	type TaskCategoryTypes,
	type ViewportCreationDefinition,
};

export interface ShapeDiverResponseOutputContent extends ShapeDiverResponseOutputContentBackend {
	// #region Properties (1)

	data?:
		| ITag2D[]
		| ITag3D[]
		| IAnchor[]
		| IMaterialContentData
		| IMaterialContentDataV1
		| IMaterialContentDataV2
		| IMaterialContentDataV3
		| unknown;

	// #endregion Properties (1)
}
export interface ShapeDiverResponseOutputChunk extends ShapeDiverResponseOutputChunkBackend {
	// #region Properties (1)

	node?: ITreeNode;

	// #endregion Properties (1)
}
