import {
	ResExportDefinitionType as EXPORT_TYPE,
	ResExport as ShapeDiverResponseExport,
	ResExportContent as ShapeDiverResponseExportContent,
	ReqExportDefinitionGroup as ShapeDiverResponseExportDefinitionGroup,
	ResExportResult as ShapeDiverResponseExportResult,
	ResModelComputationStats as ShapeDiverResponseModelComputationStatus,
	ResOutput as ShapeDiverResponseOutput,
	ResOutputChunk as ShapeDiverResponseOutputChunkBackend,
	ResOutputContent as ShapeDiverResponseOutputContentBackend,
	ResParameter as ShapeDiverResponseParameter,
} from "@shapediver/sdk.geometry-api-sdk-v2";
import {
	addListener,
	generalOptions,
	type IGeneralOptions,
	removeListener,
	sceneTree,
	version,
} from "@shapediver/viewer.api.general";
import {DataEngine} from "@shapediver/viewer.data-engine.data-engine";
import {GeometryEngine} from "@shapediver/viewer.data-engine.geometry-engine";
import {MaterialEngine} from "@shapediver/viewer.data-engine.material-engine";
import {
	type IAnchor,
	type IMaterialContentData,
	type IMaterialContentDataV1,
	type IMaterialContentDataV2,
	type IMaterialContentDataV3,
	type ITag2D,
	type ITag3D,
	type ITexture,
	TAG3D_JUSTIFICATION,
} from "@shapediver/viewer.data-engine.shared-types";
import {
	CAMERA_TYPE,
	type ICameraOptions,
	ORTHOGRAPHIC_CAMERA_DIRECTION,
	type OrthographicCameraProperties,
	type PerspectiveCameraProperties,
} from "@shapediver/viewer.rendering-engine.camera-engine";
import {LIGHT_TYPE} from "@shapediver/viewer.rendering-engine.light-engine";
import {
	BlendFunction,
	BloomEffect,
	ChromaticAberrationEffect,
	DepthOfFieldEffect,
	DotScreenEffect,
	Effect,
	EffectComposer,
	ENVIRONMENT_MAP,
	ENVIRONMENT_MAP_CUBE,
	ENVIRONMENT_MAP_EMPTY,
	GodRaysEffect,
	GridEffect,
	HueSaturationEffect,
	type IThreejsData,
	KernelSize,
	NoiseEffect,
	OutlineEffect,
	PixelationEffect,
	Resolution,
	ScanlineEffect,
	SelectiveBloomEffect,
	SepiaEffect,
	SSAOEffect,
	ThreejsData,
	TiltShiftEffect,
	VignetteEffect,
	VignetteTechnique,
} from "@shapediver/viewer.rendering-engine.rendering-engine-threejs";
import {
	Box,
	type IBox,
	type IGeometry,
	type ISphere,
	Sphere,
} from "@shapediver/viewer.shared.math";
import {
	AnimationData,
	AttributeData,
	ChunkData,
	CustomData,
	GeometryData,
	HTMLElementAnchorCustomData,
	HTMLElementAnchorData,
	HTMLElementAnchorImageData,
	HTMLElementAnchorTextData,
	InstanceData,
	type ITransformation,
	type ITree,
	type ITreeNode,
	type ITreeNodeData,
	MapData,
	MaterialBasicLineData,
	MaterialGemData,
	MaterialLambertData,
	MaterialMultiPointData,
	MaterialPhongData,
	MaterialPointData,
	MaterialShadowData,
	MaterialSpecularGlossinessData,
	MaterialStandardData,
	MaterialUnlitData,
	MaterialVariantsData,
	PrimitiveData,
	SDTFAttributeData,
	SDTFAttributesData,
	SDTFItemData,
	SDTFOverviewData,
	Tree,
	TreeNode,
} from "@shapediver/viewer.shared.node-tree";
import {
	Converter,
	defaultSettings,
	EVENTTYPE,
	EVENTTYPE_CAMERA,
	EVENTTYPE_DRAWING_TOOLS,
	EVENTTYPE_INTERACTION,
	EVENTTYPE_OUTPUT,
	EVENTTYPE_PARAMETER,
	EVENTTYPE_RENDERING,
	EVENTTYPE_SCENE,
	EVENTTYPE_SESSION,
	EVENTTYPE_TASK,
	EVENTTYPE_TRANSFORMATION_TOOLS,
	EVENTTYPE_VIEWPORT,
	type IDomEventListener,
	type IEvent,
	isARError,
	isValid,
	isViewerCameraError,
	isViewerCustomizationError,
	isViewerDataProcessingError,
	isViewerDrawingToolsError,
	isViewerEnvironmentMapError,
	isViewerError,
	isViewerGeometryBackendError,
	isViewerGeometryBackendGenericError,
	isViewerGeometryBackendRequestError,
	isViewerGeometryBackendResponseError,
	isViewerInteractionError,
	isViewerLightError,
	isViewerSessionError,
	isViewerSettingsError,
	isViewerUnknownError,
	isViewerValidationError,
	isViewerViewportError,
	isViewerWebGLError,
	LOGGING_LEVEL,
	type MainEventTypes,
	SESSION_SETTINGS_MODE,
	ShapeDiverGeometryBackendError,
	ShapeDiverGeometryBackendRequestError,
	ShapeDiverGeometryBackendResponseError,
	ShapeDiverGeometryBackendResponseErrorType,
	ShapeDiverViewerArError,
	ShapeDiverViewerCameraError,
	ShapeDiverViewerCustomizationError,
	ShapeDiverViewerDataProcessingError,
	ShapeDiverViewerDrawingToolsError,
	ShapeDiverViewerEnvironmentMapError,
	ShapeDiverViewerError,
	ShapeDiverViewerErrorType,
	ShapeDiverViewerInteractionError,
	ShapeDiverViewerLightError,
	ShapeDiverViewerSessionError,
	ShapeDiverViewerSettingsError,
	ShapeDiverViewerUnknownError,
	ShapeDiverViewerValidationError,
	ShapeDiverViewerViewportError,
	ShapeDiverViewerWebGLError,
	stringify,
	SystemInfo,
} from "@shapediver/viewer.shared.services";
import {
	ANTI_ALIASING_TECHNIQUE,
	BUSY_MODE_DISPLAY,
	type DraggingParameterValue,
	type DrawingParameterValue,
	type EventResponseMapping,
	FLAG_TYPE,
	type GumballTransformParameterValue,
	type IAnchorDataImage,
	type IAnchorDataText,
	type IAnimationData,
	type IAnimationTrack,
	type IAttributeData,
	type IBloomEffectDefinition,
	type ICameraEvent,
	type IChromaticAberrationEffectDefinition,
	type IChunkData,
	type ICustomData,
	type IDepthOfFieldEffectDefinition,
	type IDotScreenEffectDefinition,
	IDraggingParameterJsonSchema,
	type IDraggingParameterProps,
	IDraggingParameterPropsJsonSchema,
	IDrawingParameterJsonSchema,
	type IDrawingParameterSettings,
	type IGeometryData,
	type IGodRaysEffectDefinition,
	type IGridEffectDefinition,
	IGumballTransformParameterJsonSchema,
	type IGumballTransformParameterProps,
	IGumballTransformParameterPropsJsonSchema,
	type IHBAOEffectDefinition,
	type IHTMLElementAnchorData,
	type IHTMLElementAnchorUpdateProperties,
	type IHueSaturationEffectDefinition,
	type IInstanceData,
	IInteractionParameterJsonSchema,
	type IInteractionParameterProps,
	type IInteractionParameterSettings,
	type IMapData,
	type IMapDataProperties,
	type IMapDataPropertiesDefinition,
	type IMaterialAbstractData,
	type IMaterialAbstractDataProperties,
	type IMaterialAbstractDataPropertiesDefinition,
	type IMaterialBasicLineData,
	type IMaterialBasicLineDataProperties,
	type IMaterialBasicLineDataPropertiesDefinition,
	type IMaterialGemData,
	type IMaterialGemDataProperties,
	type IMaterialGemDataPropertiesDefinition,
	type IMaterialLambertData,
	type IMaterialLambertDataProperties,
	type IMaterialLambertDataPropertiesDefinition,
	type IMaterialMultiPointData,
	type IMaterialMultiPointDataProperties,
	type IMaterialMultiPointDataPropertiesDefinition,
	type IMaterialPhongData,
	type IMaterialPhongDataProperties,
	type IMaterialPhongDataPropertiesDefinition,
	type IMaterialPointData,
	type IMaterialPointDataProperties,
	type IMaterialPointDataPropertiesDefinition,
	type IMaterialShadowData,
	type IMaterialShadowDataProperties,
	type IMaterialShadowDataPropertiesDefinition,
	type IMaterialSpecularGlossinessData,
	type IMaterialSpecularGlossinessDataProperties,
	type IMaterialSpecularGlossinessDataPropertiesDefinition,
	type IMaterialStandardData,
	type IMaterialStandardDataProperties,
	type IMaterialStandardDataPropertiesDefinition,
	type IMaterialUnlitData,
	type IMaterialUnlitDataProperties,
	type IMaterialUnlitDataPropertiesDefinition,
	type IMaterialVariantsData,
	type INoiseEffectDefinition,
	type InteractionParameterSettingsType,
	type IOutlineEffectDefinition,
	type IOutputEvent,
	type IParameterEvent,
	type IPixelationEffectDefinition,
	type IPostProcessingEffectDefinition,
	type IPrimitiveData,
	type IPulseEffectDefinition,
	IRectangleTransformParameterJsonSchema,
	type IRectangleTransformParameterProps,
	IRectangleTransformParameterPropsJsonSchema,
	type IRenderingEvent,
	type IScanlineEffectDefinition,
	type ISceneEvent,
	type ISDTFAttributeData,
	type ISDTFAttributesData,
	type ISDTFAttributeVisualizationData,
	type ISDTFItemData,
	type ISDTFOverview,
	type ISDTFOverviewData,
	ISelectionParameterJsonSchema,
	type ISelectionParameterProps,
	ISelectionParameterPropsJsonSchema,
	type ISelectiveBloomEffectDefinition,
	type ISepiaEffectDefinition,
	type ISessionErrorEvent,
	type ISessionEvent,
	type ISessionSettingsSections,
	type ISettingsSections,
	type ISSAOEffectDefinition,
	type ITaskEvent,
	type ITaskEventDescription,
	type ITiltShiftEffectDefinition,
	type IViewportEvent,
	type IViewportSettingsSections,
	type IVignetteEffectDefinition,
	MATERIAL_ALPHA,
	MATERIAL_SHADING,
	MATERIAL_SIDE,
	MATERIAL_TYPE,
	PARAMETER_TYPE,
	PARAMETER_VISUALIZATION,
	POST_PROCESSING_EFFECT_TYPE,
	PRIMITIVE_MODE,
	type RectangleTransformParameterValue,
	RENDERER_TYPE,
	SDTF_TYPEHINT,
	SdtfPrimitiveTypeGuard,
	type SelectionParameterValue,
	type SessionCreationDefinition,
	SPINNER_POSITIONING,
	TASK_CATEGORY,
	TASK_CATEGORY_SESSION_CUSTOMIZATION_CATEGORY,
	TASK_TYPE,
	type TaskCategoryTypes,
	TEXTURE_ENCODING,
	TEXTURE_FILTERING,
	TEXTURE_WRAPPING,
	TONE_MAPPING,
	validateDraggingParameterSettings,
	validateDrawingParameterSettings,
	validateGumballTransformParameterSettings,
	validateInteractionParameterSettings,
	validateRectangleTransformParameterSettings,
	validateSelectionParameterSettings,
	type ViewportCreationDefinition,
	VISIBILITY_MODE,
} from "@shapediver/viewer.shared.types";
import {type ICameraApi} from "./interfaces/camera/ICameraApi";
import {type IOrthographicCameraApi} from "./interfaces/camera/IOrthographicCameraApi";
import {type IPerspectiveCameraApi} from "./interfaces/camera/IPerspectiveCameraApi";
import {type IPostProcessingApi} from "./interfaces/IPostProcessingApi";
import {type IViewportApi} from "./interfaces/IViewportApi";
import {type ILightApi} from "./interfaces/lights/ILightApi";
import {type ILightSceneApi} from "./interfaces/lights/ILightSceneApi";
import {type IAmbientLightApi} from "./interfaces/lights/types/IAmbientLightApi";
import {type IDirectionalLightApi} from "./interfaces/lights/types/IDirectionalLightApi";
import {type IHemisphereLightApi} from "./interfaces/lights/types/IHemisphereLightApi";
import {type IPointLightApi} from "./interfaces/lights/types/IPointLightApi";
import {type ISpotLightApi} from "./interfaces/lights/types/ISpotLightApi";
import {createViewport, viewports} from "./main";

export {
	addListener,
	AnimationData,
	ANTI_ALIASING_TECHNIQUE,
	AttributeData,
	BlendFunction,
	BloomEffect,
	Box,
	BUSY_MODE_DISPLAY,
	CAMERA_TYPE,
	ChromaticAberrationEffect,
	ChunkData,
	Converter,
	createViewport,
	CustomData,
	DataEngine,
	defaultSettings,
	DepthOfFieldEffect,
	DotScreenEffect,
	Effect,
	EffectComposer,
	ENVIRONMENT_MAP,
	ENVIRONMENT_MAP_CUBE,
	ENVIRONMENT_MAP_EMPTY,
	EVENTTYPE,
	EVENTTYPE_CAMERA,
	EVENTTYPE_DRAWING_TOOLS,
	EVENTTYPE_INTERACTION,
	EVENTTYPE_OUTPUT,
	EVENTTYPE_PARAMETER,
	EVENTTYPE_RENDERING,
	EVENTTYPE_SCENE,
	EVENTTYPE_SESSION,
	EVENTTYPE_TASK,
	EVENTTYPE_TRANSFORMATION_TOOLS,
	EVENTTYPE_VIEWPORT,
	EXPORT_TYPE,
	FLAG_TYPE,
	generalOptions,
	GeometryData,
	GeometryEngine,
	GodRaysEffect,
	GridEffect,
	HTMLElementAnchorCustomData,
	HTMLElementAnchorData,
	HTMLElementAnchorImageData,
	HTMLElementAnchorTextData,
	HueSaturationEffect,
	IDraggingParameterJsonSchema,
	IDraggingParameterPropsJsonSchema,
	IDrawingParameterJsonSchema,
	IGumballTransformParameterJsonSchema,
	IGumballTransformParameterPropsJsonSchema,
	IInteractionParameterJsonSchema,
	InstanceData,
	IRectangleTransformParameterJsonSchema,
	IRectangleTransformParameterPropsJsonSchema,
	isARError,
	ISelectionParameterJsonSchema,
	ISelectionParameterPropsJsonSchema,
	isValid,
	isViewerCameraError,
	isViewerCustomizationError,
	isViewerDataProcessingError,
	isViewerDrawingToolsError,
	isViewerEnvironmentMapError,
	isViewerError,
	isViewerGeometryBackendError,
	isViewerGeometryBackendGenericError,
	isViewerGeometryBackendRequestError,
	isViewerGeometryBackendResponseError,
	isViewerInteractionError,
	isViewerLightError,
	isViewerSessionError,
	isViewerSettingsError,
	isViewerUnknownError,
	isViewerValidationError,
	isViewerViewportError,
	isViewerWebGLError,
	KernelSize,
	LIGHT_TYPE,
	LOGGING_LEVEL,
	MapData,
	MATERIAL_ALPHA,
	MATERIAL_SHADING,
	MATERIAL_SIDE,
	MATERIAL_TYPE,
	MaterialBasicLineData,
	MaterialEngine,
	MaterialGemData,
	MaterialLambertData,
	MaterialMultiPointData,
	MaterialPhongData,
	MaterialPointData,
	MaterialShadowData,
	MaterialSpecularGlossinessData,
	MaterialStandardData,
	MaterialUnlitData,
	MaterialVariantsData,
	NoiseEffect,
	ORTHOGRAPHIC_CAMERA_DIRECTION,
	OutlineEffect,
	PARAMETER_TYPE,
	PARAMETER_VISUALIZATION,
	PixelationEffect,
	POST_PROCESSING_EFFECT_TYPE,
	PRIMITIVE_MODE,
	PrimitiveData,
	removeListener,
	RENDERER_TYPE,
	Resolution,
	ScanlineEffect,
	sceneTree,
	SDTF_TYPEHINT,
	SDTFAttributeData,
	SDTFAttributesData,
	SDTFItemData,
	SDTFOverviewData,
	SdtfPrimitiveTypeGuard,
	SelectiveBloomEffect,
	SepiaEffect,
	SESSION_SETTINGS_MODE,
	ShapeDiverGeometryBackendError,
	ShapeDiverGeometryBackendRequestError,
	ShapeDiverGeometryBackendResponseError,
	ShapeDiverGeometryBackendResponseErrorType,
	ShapeDiverResponseExport,
	ShapeDiverResponseExportContent,
	ShapeDiverResponseExportDefinitionGroup,
	ShapeDiverResponseExportResult,
	ShapeDiverResponseModelComputationStatus,
	ShapeDiverResponseOutput,
	ShapeDiverResponseOutputChunkBackend,
	ShapeDiverResponseOutputContentBackend,
	ShapeDiverResponseParameter,
	ShapeDiverViewerArError,
	ShapeDiverViewerCameraError,
	ShapeDiverViewerCustomizationError,
	ShapeDiverViewerDataProcessingError,
	ShapeDiverViewerDrawingToolsError,
	ShapeDiverViewerEnvironmentMapError,
	ShapeDiverViewerError,
	ShapeDiverViewerErrorType,
	ShapeDiverViewerInteractionError,
	ShapeDiverViewerLightError,
	ShapeDiverViewerSessionError,
	ShapeDiverViewerSettingsError,
	ShapeDiverViewerUnknownError,
	ShapeDiverViewerValidationError,
	ShapeDiverViewerViewportError,
	ShapeDiverViewerWebGLError,
	Sphere,
	SPINNER_POSITIONING,
	SSAOEffect,
	stringify,
	SystemInfo,
	TAG3D_JUSTIFICATION,
	TASK_CATEGORY,
	TASK_CATEGORY_SESSION_CUSTOMIZATION_CATEGORY,
	TASK_TYPE,
	TEXTURE_ENCODING,
	TEXTURE_FILTERING,
	TEXTURE_WRAPPING,
	ThreejsData,
	TiltShiftEffect,
	TONE_MAPPING,
	Tree,
	TreeNode,
	validateDraggingParameterSettings,
	validateDrawingParameterSettings,
	validateGumballTransformParameterSettings,
	validateInteractionParameterSettings,
	validateRectangleTransformParameterSettings,
	validateSelectionParameterSettings,
	version,
	viewports,
	VignetteEffect,
	VignetteTechnique,
	VISIBILITY_MODE,
};
export type {
	DraggingParameterValue,
	DrawingParameterValue,
	EventResponseMapping,
	GumballTransformParameterValue,
	IAmbientLightApi,
	IAnchorDataImage,
	IAnchorDataText,
	IAnimationData,
	IAnimationTrack,
	IAttributeData,
	IBloomEffectDefinition,
	IBox,
	ICameraApi,
	ICameraEvent,
	ICameraOptions,
	IChromaticAberrationEffectDefinition,
	IChunkData,
	ICustomData,
	IDepthOfFieldEffectDefinition,
	IDirectionalLightApi,
	IDomEventListener,
	IDotScreenEffectDefinition,
	IDraggingParameterProps,
	IDrawingParameterSettings,
	IEvent,
	IGeneralOptions,
	IGeometry,
	IGeometryData,
	IGodRaysEffectDefinition,
	IGridEffectDefinition,
	IGumballTransformParameterProps,
	IHBAOEffectDefinition,
	IHemisphereLightApi,
	IHTMLElementAnchorData,
	IHTMLElementAnchorUpdateProperties,
	IHueSaturationEffectDefinition,
	IInstanceData,
	IInteractionParameterProps,
	IInteractionParameterSettings,
	ILightApi,
	ILightSceneApi,
	IMapData,
	IMapDataProperties,
	IMapDataPropertiesDefinition,
	IMaterialAbstractData,
	IMaterialAbstractDataProperties,
	IMaterialAbstractDataPropertiesDefinition,
	IMaterialBasicLineData,
	IMaterialBasicLineDataProperties,
	IMaterialBasicLineDataPropertiesDefinition,
	IMaterialGemData,
	IMaterialGemDataProperties,
	IMaterialGemDataPropertiesDefinition,
	IMaterialLambertData,
	IMaterialLambertDataProperties,
	IMaterialLambertDataPropertiesDefinition,
	IMaterialMultiPointData,
	IMaterialMultiPointDataProperties,
	IMaterialMultiPointDataPropertiesDefinition,
	IMaterialPhongData,
	IMaterialPhongDataProperties,
	IMaterialPhongDataPropertiesDefinition,
	IMaterialPointData,
	IMaterialPointDataProperties,
	IMaterialPointDataPropertiesDefinition,
	IMaterialShadowData,
	IMaterialShadowDataProperties,
	IMaterialShadowDataPropertiesDefinition,
	IMaterialSpecularGlossinessData,
	IMaterialSpecularGlossinessDataProperties,
	IMaterialSpecularGlossinessDataPropertiesDefinition,
	IMaterialStandardData,
	IMaterialStandardDataProperties,
	IMaterialStandardDataPropertiesDefinition,
	IMaterialUnlitData,
	IMaterialUnlitDataProperties,
	IMaterialUnlitDataPropertiesDefinition,
	IMaterialVariantsData,
	INoiseEffectDefinition,
	InteractionParameterSettingsType,
	IOrthographicCameraApi,
	IOutlineEffectDefinition,
	IOutputEvent,
	IParameterEvent,
	IPerspectiveCameraApi,
	IPixelationEffectDefinition,
	IPointLightApi,
	IPostProcessingApi,
	IPostProcessingEffectDefinition,
	IPrimitiveData,
	IPulseEffectDefinition,
	IRectangleTransformParameterProps,
	IRenderingEvent,
	IScanlineEffectDefinition,
	ISceneEvent,
	ISDTFAttributeData,
	ISDTFAttributesData,
	ISDTFAttributeVisualizationData,
	ISDTFItemData,
	ISDTFOverview,
	ISDTFOverviewData,
	ISelectionParameterProps,
	ISelectiveBloomEffectDefinition,
	ISepiaEffectDefinition,
	ISessionErrorEvent,
	ISessionEvent,
	ISessionSettingsSections,
	ISettingsSections,
	ISphere,
	ISpotLightApi,
	ISSAOEffectDefinition,
	ITag2D,
	ITag3D,
	ITaskEvent,
	ITaskEventDescription,
	ITexture,
	IThreejsData,
	ITiltShiftEffectDefinition,
	ITransformation,
	ITree,
	ITreeNode,
	ITreeNodeData,
	IViewportApi,
	IViewportEvent,
	IViewportSettingsSections,
	IVignetteEffectDefinition,
	MainEventTypes,
	OrthographicCameraProperties,
	PerspectiveCameraProperties,
	RectangleTransformParameterValue,
	SelectionParameterValue,
	SessionCreationDefinition,
	TaskCategoryTypes,
	ViewportCreationDefinition,
};

export interface ShapeDiverResponseOutputContent extends ShapeDiverResponseOutputContentBackend {
	// #region Properties (1)

	data?:
		| ITag2D[]
		| ITag3D[]
		| IAnchor[]
		| IMaterialContentData
		| IMaterialContentDataV1
		| IMaterialContentDataV2
		| IMaterialContentDataV3
		| unknown;

	// #endregion Properties (1)
}
export interface ShapeDiverResponseOutputChunk extends ShapeDiverResponseOutputChunkBackend {
	// #region Properties (1)

	node?: ITreeNode;

	// #endregion Properties (1)
}
